package org.stellar.sdk.responses;

import java.io.IOException;
import junit.framework.TestCase;
import org.junit.Test;
import org.stellar.sdk.Memo;
import org.stellar.sdk.xdr.OperationType;
import org.stellar.sdk.xdr.TransactionResult;
import org.stellar.sdk.xdr.TransactionResultCode;

public class SubmitTransactionResponseTest extends TestCase {
  @Test
  public void testDeserializeTransactionFailureResponse() throws IOException {
    String json =
        "{\n"
            + "  \"type\": \"https://developers.stellar.org/api/errors/http-status-codes/horizon-specific/transaction-failed/\",\n"
            + "  \"title\": \"Transaction Failed\",\n"
            + "  \"status\": 400,\n"
            + "  \"detail\": \"The transaction failed when submitted to the stellar network. The `extras.result_codes` field on this response contains further details.  Descriptions of each code can be found at: https://developers.stellar.org/docs/start/list-of-operations/\",\n"
            + "  \"instance\": \"horizon-testnet-001.prd.stellar001.internal.stellar-ops.com/4elYz2fHhC-528285\",\n"
            + "  \"extras\": {\n"
            + "    \"envelope_xdr\": \"AAAAAKpmDL6Z4hvZmkTBkYpHftan4ogzTaO4XTB7joLgQnYYAAAAZAAAAAAABeoyAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAD3sEVVGZGi/NoC3ta/8f/YZKMzyi9ZJpOi0H47x7IqYAAAAAAAAAAAF9eEAAAAAAAAAAAA=\",\n"
            + "    \"result_codes\": {\n"
            + "      \"transaction\": \"tx_no_source_account\"\n"
            + "    },\n"
            + "    \"result_xdr\": \"AAAAAAAAAAD////4AAAAAA==\"\n"
            + "  }\n"
            + "}";

    SubmitTransactionResponse submitTransactionResponse =
        GsonSingleton.getInstance().fromJson(json, SubmitTransactionResponse.class);
    assertFalse(submitTransactionResponse.isSuccess());
    assertNull(submitTransactionResponse.getEnvelopeXdr());
    assertNull(submitTransactionResponse.getResultMetaXdr());
    assertFalse(submitTransactionResponse.getOfferIdFromResult(0).isPresent());
    assertFalse(submitTransactionResponse.getDecodedTransactionResult().isPresent());
    assertEquals(
        submitTransactionResponse.getExtras().getResultCodes().getTransactionResultCode(),
        "tx_no_source_account");
  }

  @Test
  public void testDeserializeFeeBumpTransactionFailureResponse() throws IOException {
    String json =
        "{\n"
            + "  \"type\": \"https://developers.stellar.org/api/errors/http-status-codes/horizon-specific/transaction-failed/\",\n"
            + "  \"title\": \"Transaction Failed\",\n"
            + "  \"status\": 400,\n"
            + "  \"detail\": \"The transaction failed when submitted to the stellar network. The `extras.result_codes` field on this response contains further details.  Descriptions of each code can be found at: https://developers.stellar.org/docs/start/list-of-operations/\",\n"
            + "  \"instance\": \"horizon-testnet-001.prd.stellar001.internal.stellar-ops.com/4elYz2fHhC-528285\",\n"
            + "  \"extras\": {\n"
            + "    \"envelope_xdr\": \"AAAAAKpmDL6Z4hvZmkTBkYpHftan4ogzTaO4XTB7joLgQnYYAAAAZAAAAAAABeoyAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAD3sEVVGZGi/NoC3ta/8f/YZKMzyi9ZJpOi0H47x7IqYAAAAAAAAAAAF9eEAAAAAAAAAAAA=\",\n"
            + "    \"result_codes\": {\n"
            + "      \"transaction\": \"tx_fee_bump_inner_failed\",\n"
            + "      \"inner_transaction\": \"tx_no_source_account\"\n"
            + "    },\n"
            + "    \"result_xdr\": \"AAAAAAAAAMj////zxZjN9tKJLJ6diZuWBitlMJ/4MXX1Akm9M5CqZt10ogoAAAAAAAAAAP////8AAAABAAAAAAAAAAb/////AAAAAAAAAAA=\"\n"
            + "  }\n"
            + "}";

    SubmitTransactionResponse submitTransactionResponse =
        GsonSingleton.getInstance().fromJson(json, SubmitTransactionResponse.class);
    assertFalse(submitTransactionResponse.isSuccess());
    assertNull(submitTransactionResponse.getEnvelopeXdr());
    assertNull(submitTransactionResponse.getResultMetaXdr());
    assertFalse(submitTransactionResponse.getOfferIdFromResult(0).isPresent());
    assertFalse(submitTransactionResponse.getDecodedTransactionResult().isPresent());
    assertEquals(
        submitTransactionResponse.getExtras().getResultCodes().getTransactionResultCode(),
        "tx_fee_bump_inner_failed");
    assertEquals(
        submitTransactionResponse.getExtras().getResultCodes().getInnerTransactionResultCode(),
        "tx_no_source_account");
  }

  @Test
  public void testDeserializeOperationFailureResponse() throws IOException {
    String json =
        "{\n"
            + "  \"type\": \"https://developers.stellar.org/api/errors/http-status-codes/horizon-specific/transaction-failed/\",\n"
            + "  \"title\": \"Transaction Failed\",\n"
            + "  \"status\": 400,\n"
            + "  \"detail\": \"The transaction failed when submitted to the stellar network. The `extras.result_codes` field on this response contains further details.  Descriptions of each code can be found at: https://developers.stellar.org/docs/start/list-of-operations/\",\n"
            + "  \"instance\": \"horizon-testnet-001.prd.stellar001.internal.stellar-ops.com/4elYz2fHhC-528366\",\n"
            + "  \"extras\": {\n"
            + "    \"envelope_xdr\": \"AAAAAF2O0axA67+p2jMunG6G188kDSHIvqQ13d9l29YCSA/uAAAAZAAvvc0AAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAD3sEVVGZGi/NoC3ta/8f/YZKMzyi9ZJpOi0H47x7IqYAAAAAAAAAAAF9eEAAAAAAAAAAAECSA/uAAAAQFuZVAjftHa+JZes1VxSk8naOfjjAz9V86mY1AZf8Ik6PtTsBpDsCfG57EYsq4jWyZcT+vhXyWsw5evF1ELqMw4=\",\n"
            + "    \"result_codes\": {\n"
            + "      \"transaction\": \"tx_failed\",\n"
            + "      \"operations\": [\n"
            + "        \"op_no_destination\"\n"
            + "      ]\n"
            + "    },\n"
            + "    \"result_xdr\": \"AAAAAAAAAGT/////AAAAAQAAAAAAAAAB////+wAAAAA=\"\n"
            + "  }\n"
            + "}";

    SubmitTransactionResponse submitTransactionResponse =
        GsonSingleton.getInstance().fromJson(json, SubmitTransactionResponse.class);
    assertFalse(submitTransactionResponse.isSuccess());
    assertNull(submitTransactionResponse.getEnvelopeXdr());
    assertNull(submitTransactionResponse.getResultMetaXdr());
    assertFalse(submitTransactionResponse.getOfferIdFromResult(0).isPresent());
    assertFalse(submitTransactionResponse.getDecodedTransactionResult().isPresent());
    assertEquals(
        submitTransactionResponse.getExtras().getResultCodes().getTransactionResultCode(),
        "tx_failed");
    assertEquals(
        submitTransactionResponse.getExtras().getResultCodes().getOperationsResultCodes().get(0),
        "op_no_destination");
  }

  @Test
  public void testDeserializeSuccessResponse() throws IOException {
    String json =
        "{\n"
            + "  \"_links\": {\n"
            + "    \"self\": {\n"
            + "      \"href\": \"https://horizon.stellar.org/transactions/55d0085f71daaf5950895c0a28af0ba0c60a33f5eb6defed06945e435f3bff92\"\n"
            + "    },\n"
            + "    \"account\": {\n"
            + "      \"href\": \"https://horizon.stellar.org/accounts/GD27YXGHRZFQHQH6O5HZ32TFWR5X46Q4ONQ5YV2KX6M3J7J2Z45IBCHM\"\n"
            + "    },\n"
            + "    \"ledger\": {\n"
            + "      \"href\": \"https://horizon.stellar.org/ledgers/51013692\"\n"
            + "    },\n"
            + "    \"operations\": {\n"
            + "      \"href\": \"https://horizon.stellar.org/transactions/55d0085f71daaf5950895c0a28af0ba0c60a33f5eb6defed06945e435f3bff92/operations{?cursor,limit,order}\",\n"
            + "      \"templated\": true\n"
            + "    },\n"
            + "    \"effects\": {\n"
            + "      \"href\": \"https://horizon.stellar.org/transactions/55d0085f71daaf5950895c0a28af0ba0c60a33f5eb6defed06945e435f3bff92/effects{?cursor,limit,order}\",\n"
            + "      \"templated\": true\n"
            + "    },\n"
            + "    \"precedes\": {\n"
            + "      \"href\": \"https://horizon.stellar.org/transactions?order=asc&cursor=219102138789228544\"\n"
            + "    },\n"
            + "    \"succeeds\": {\n"
            + "      \"href\": \"https://horizon.stellar.org/transactions?order=desc&cursor=219102138789228544\"\n"
            + "    },\n"
            + "    \"transaction\": {\n"
            + "      \"href\": \"https://horizon.stellar.org/transactions/55d0085f71daaf5950895c0a28af0ba0c60a33f5eb6defed06945e435f3bff92\"\n"
            + "    }\n"
            + "  },\n"
            + "  \"id\": \"55d0085f71daaf5950895c0a28af0ba0c60a33f5eb6defed06945e435f3bff92\",\n"
            + "  \"paging_token\": \"219102138789228544\",\n"
            + "  \"successful\": true,\n"
            + "  \"hash\": \"55d0085f71daaf5950895c0a28af0ba0c60a33f5eb6defed06945e435f3bff92\",\n"
            + "  \"ledger\": 51013692,\n"
            + "  \"created_at\": \"2024-03-30T07:50:20Z\",\n"
            + "  \"source_account\": \"GD27YXGHRZFQHQH6O5HZ32TFWR5X46Q4ONQ5YV2KX6M3J7J2Z45IBCHM\",\n"
            + "  \"source_account_sequence\": \"218925452423618068\",\n"
            + "  \"fee_account\": \"GD27YXGHRZFQHQH6O5HZ32TFWR5X46Q4ONQ5YV2KX6M3J7J2Z45IBCHM\",\n"
            + "  \"fee_charged\": \"800\",\n"
            + "  \"max_fee\": \"800000\",\n"
            + "  \"operation_count\": 8,\n"
            + "  \"envelope_xdr\": \"AAAAAgAAAAD1/FzHjksDwP53T53qZbR7fnocc2HcV0q/mbT9Os86gAAMNQADCceKAABeFAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAABAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAADAAAAAFVU0RDAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAAAAAAAAADMRusABVTPwCYloAAAAAAWdc06QAAAAEAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAAAMAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAAAAAAAA9/SQIAFVEPAJiWgAAAAABZ10JyAAAAAQAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAAMAAAAAAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAAD39JAAAVVW8AmJaAAAAAAFnXMoYAAAABAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAAwAAAAAAAAABVVNEQwAAAAA7mRE4Dv6Yi6CokA6xz+RPNm99vpRr7QdyQPf2JN8VxQAAAAAPf0kAAAqrFQBMS0AAAAAAWdcyhwAAAAEAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAAADAAAAAAAAAAFVU0RDAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAAAA9/SQAAFVblAJiWgAAAAABZ1zKIAAAAAQAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAAMAAAAAAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAAD39JAAAVV58AmJaAAAAAAFnXNlgAAAABAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAADAAAAAFVU0RDAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAAAAAAAAAPf0j/AAEQ7QAHoSAAAAAAWdc06gAAAAEAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAAAMAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAAAAAAAA9/SQAAFVHJAJiWgAAAAABZ10JxAAAAAAAAAAI6zzqAAAAAQJCw/VwsxqScZabga+2urpx/7hQQYyA1dw9aec5xKZZw9MyBvOFCgEY4kP4a8AZPJ5w0aieHRQFsekTZyup9qQyS2fkeAAAAQAXxtwmlqQna0MLjgR3cXPcZwzKm1wEKG1fjEMGlY0dPpH5fs2jZU8s2jjONYWHiRPLuxur6Srpd6sJq2e1nUwo=\",\n"
            + "  \"result_xdr\": \"AAAAAAAAAyAAAAAAAAAACAAAAAAAAAAMAAAAAAAAAAAAAAABAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAAFnXNOkAAAABVVNEQwAAAAA7mRE4Dv6Yi6CokA6xz+RPNm99vpRr7QdyQPf2JN8VxQAAAAAAAAAAAHIyQgCYloAAFVM/AAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAQAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAABZ10JyAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAAAAAAAAIqO4YAmJaAABVRDwAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAEAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAAAAWdcyhgAAAAAAAAABVVNEQwAAAAA7mRE4Dv6Yi6CokA6xz+RPNm99vpRr7QdyQPf2JN8VxQAAAAAPf0kAABVVbwCYloAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAABAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAAFnXMocAAAAAAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAAD39JAAAKqxUATEtAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAQAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAABZ1zKIAAAAAAAAAAFVU0RDAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAAAA9/SQAAFVblAJiWgAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAEAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAAAAWdc2WAAAAAAAAAABVVNEQwAAAAA7mRE4Dv6Yi6CokA6xz+RPNm99vpRr7QdyQPf2JN8VxQAAAAAPf0kAABVXnwCYloAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAABAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAAFnXNOoAAAABVVNEQwAAAAA7mRE4Dv6Yi6CokA6xz+RPNm99vpRr7QdyQPf2JN8VxQAAAAAAAAAAAiphZwAHoSAAARDtAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAQAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAABZ10JxAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAAAAAAAAIqTmoAmJaAABVRyQAAAAAAAAAAAAAAAA==\",\n"
            + "  \"result_meta_xdr\": \"AAAAAwAAAAAAAAACAAAAAwMKaDwAAAAAAAAAAPX8XMeOSwPA/ndPnepltHt+ehxzYdxXSr+ZtP06zzqAAAAAASq6zgMDCceKAABeEwAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAMAAAAAAwpoOwAAAABmB8Q2AAAAAAAAAAEDCmg8AAAAAAAAAAD1/FzHjksDwP53T53qZbR7fnocc2HcV0q/mbT9Os86gAAAAAEqus4DAwnHigAAXhQAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAADAAAAAAMKaDwAAAAAZgfEPAAAAAAAAAAIAAAABgAAAAMDCmg7AAAAAgAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAABZ1zTpAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAAAAAAAAByMkIAmJaAABVTPwAAAAAAAAAAAAAAAAAAAAEDCmg8AAAAAgAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAABZ1zTpAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAAAAAAAAByMkIAmJaAABVTPwAAAAAAAAAAAAAAAAAAAAMDCmg7AAAAAAAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAFwMfTDQAwnHigAAAAQAAAAKAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAADGu9p4AAAAAPf0kAAAAAAIAAAAAAAAAAAAAAAAAAAADAAAAAAMKZ4YAAAAAZgfAGgAAAAAAAAABAwpoPAAAAAAAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAABcDH0w0AMJx4oAAAAEAAAACgAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAxrvaeAAAAAD39JAAAAAACAAAAAAAAAAAAAAAAAAAAAwAAAAADCmeGAAAAAGYHwBoAAAAAAAAAAwMKaDsAAAABAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAKikqTmn//////////AAAAAQAAAAEAAAAACKsm8gAAAAAG8R2ZAAAAAAAAAAAAAAABAwpoPAAAAAEAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAAABVVNEQwAAAAA7mRE4Dv6Yi6CokA6xz+RPNm99vpRr7QdyQPf2JN8VxQAAAAqKSpOaf/////////8AAAABAAAAAQAAAAAIqybyAAAAAAbxHZkAAAAAAAAAAAAAAAYAAAADAwpoOwAAAAIAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAAAAWddCcgAAAAFVU0RDAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAAAAAAAAACKjuGAJiWgAAVUQ8AAAAAAAAAAAAAAAAAAAABAwpoPAAAAAIAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAAAAWddCcgAAAAFVU0RDAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAAAAAAAAACKjuGAJiWgAAVUQ8AAAAAAAAAAAAAAAAAAAADAwpoPAAAAAAAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAABcDH0w0AMJx4oAAAAEAAAACgAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAxrvaeAAAAAD39JAAAAAACAAAAAAAAAAAAAAAAAAAAAwAAAAADCmeGAAAAAGYHwBoAAAAAAAAAAQMKaDwAAAAAAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAXAx9MNADCceKAAAABAAAAAoAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAMa72ngAAAAA9/SQAAAAAAgAAAAAAAAAAAAAAAAAAAAMAAAAAAwpnhgAAAABmB8AaAAAAAAAAAAMDCmg8AAAAAQAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAAFVU0RDAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAACopKk5p//////////wAAAAEAAAABAAAAAAirJvIAAAAABvEdmQAAAAAAAAAAAAAAAQMKaDwAAAABAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAKikqTmn//////////AAAAAQAAAAEAAAAACKsm8gAAAAAG8R2ZAAAAAAAAAAAAAAAGAAAAAwMKaDsAAAACAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAAFnXMoYAAAAAAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAAD39JAAAVVW8AmJaAAAAAAAAAAAAAAAAAAAAAAQMKaDwAAAACAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAAFnXMoYAAAAAAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAAD39JAAAVVW8AmJaAAAAAAAAAAAAAAAAAAAAAAwMKaDwAAAABAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAKikqTmn//////////AAAAAQAAAAEAAAAACKsm8gAAAAAG8R2ZAAAAAAAAAAAAAAABAwpoPAAAAAEAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAAABVVNEQwAAAAA7mRE4Dv6Yi6CokA6xz+RPNm99vpRr7QdyQPf2JN8VxQAAAAqKSpOaf/////////8AAAABAAAAAQAAAAAIqybyAAAAAAbxHZkAAAAAAAAAAAAAAAMDCmg8AAAAAAAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAFwMfTDQAwnHigAAAAQAAAAKAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAADGu9p4AAAAAPf0kAAAAAAIAAAAAAAAAAAAAAAAAAAADAAAAAAMKZ4YAAAAAZgfAGgAAAAAAAAABAwpoPAAAAAAAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAABcDH0w0AMJx4oAAAAEAAAACgAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAxrvaeAAAAAD39JAAAAAACAAAAAAAAAAAAAAAAAAAAAwAAAAADCmeGAAAAAGYHwBoAAAAAAAAABgAAAAMDCmg7AAAAAgAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAABZ1zKHAAAAAAAAAAFVU0RDAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAAAA9/SQAACqsVAExLQAAAAAAAAAAAAAAAAAAAAAEDCmg8AAAAAgAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAABZ1zKHAAAAAAAAAAFVU0RDAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAAAA9/SQAACqsVAExLQAAAAAAAAAAAAAAAAAAAAAMDCmg8AAAAAQAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAAFVU0RDAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAACopKk5p//////////wAAAAEAAAABAAAAAAirJvIAAAAABvEdmQAAAAAAAAAAAAAAAQMKaDwAAAABAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAKikqTmn//////////AAAAAQAAAAEAAAAACKsm8gAAAAAG8R2ZAAAAAAAAAAAAAAADAwpoPAAAAAAAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAABcDH0w0AMJx4oAAAAEAAAACgAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAxrvaeAAAAAD39JAAAAAACAAAAAAAAAAAAAAAAAAAAAwAAAAADCmeGAAAAAGYHwBoAAAAAAAAAAQMKaDwAAAAAAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAXAx9MNADCceKAAAABAAAAAoAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAMa72ngAAAAA9/SQAAAAAAgAAAAAAAAAAAAAAAAAAAAMAAAAAAwpnhgAAAABmB8AaAAAAAAAAAAYAAAADAwpoOwAAAAIAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAAAAWdcyiAAAAAAAAAABVVNEQwAAAAA7mRE4Dv6Yi6CokA6xz+RPNm99vpRr7QdyQPf2JN8VxQAAAAAPf0kAABVW5QCYloAAAAAAAAAAAAAAAAAAAAABAwpoPAAAAAIAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAAAAWdcyiAAAAAAAAAABVVNEQwAAAAA7mRE4Dv6Yi6CokA6xz+RPNm99vpRr7QdyQPf2JN8VxQAAAAAPf0kAABVW5QCYloAAAAAAAAAAAAAAAAAAAAADAwpoPAAAAAEAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAAABVVNEQwAAAAA7mRE4Dv6Yi6CokA6xz+RPNm99vpRr7QdyQPf2JN8VxQAAAAqKSpOaf/////////8AAAABAAAAAQAAAAAIqybyAAAAAAbxHZkAAAAAAAAAAAAAAAEDCmg8AAAAAQAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAAFVU0RDAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAACopKk5p//////////wAAAAEAAAABAAAAAAirJvIAAAAABvEdmQAAAAAAAAAAAAAAAwMKaDwAAAAAAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAXAx9MNADCceKAAAABAAAAAoAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAMa72ngAAAAA9/SQAAAAAAgAAAAAAAAAAAAAAAAAAAAMAAAAAAwpnhgAAAABmB8AaAAAAAAAAAAEDCmg8AAAAAAAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAFwMfTDQAwnHigAAAAQAAAAKAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAADGu9p4AAAAAPf0kAAAAAAIAAAAAAAAAAAAAAAAAAAADAAAAAAMKZ4YAAAAAZgfAGgAAAAAAAAAGAAAAAwMKaDsAAAACAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAAFnXNlgAAAAAAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAAD39JAAAVV58AmJaAAAAAAAAAAAAAAAAAAAAAAQMKaDwAAAACAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAAFnXNlgAAAAAAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAAD39JAAAVV58AmJaAAAAAAAAAAAAAAAAAAAAAAwMKaDwAAAABAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAKikqTmn//////////AAAAAQAAAAEAAAAACKsm8gAAAAAG8R2ZAAAAAAAAAAAAAAABAwpoPAAAAAEAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAAABVVNEQwAAAAA7mRE4Dv6Yi6CokA6xz+RPNm99vpRr7QdyQPf2JN8VxQAAAAqKSpOaf/////////8AAAABAAAAAQAAAAAIqybyAAAAAAbxHZkAAAAAAAAAAAAAAAMDCmg8AAAAAAAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAFwMfTDQAwnHigAAAAQAAAAKAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAADGu9p4AAAAAPf0kAAAAAAIAAAAAAAAAAAAAAAAAAAADAAAAAAMKZ4YAAAAAZgfAGgAAAAAAAAABAwpoPAAAAAAAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAABcDH0w0AMJx4oAAAAEAAAACgAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAxrvaeAAAAAD39JAAAAAACAAAAAAAAAAAAAAAAAAAAAwAAAAADCmeGAAAAAGYHwBoAAAAAAAAABgAAAAMDCmg7AAAAAgAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAABZ1zTqAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAAAAAAAAIqYWcAB6EgAAEQ7QAAAAAAAAAAAAAAAAAAAAEDCmg8AAAAAgAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAABZ1zTqAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAAAAAAAAIqYWcAB6EgAAEQ7QAAAAAAAAAAAAAAAAAAAAMDCmg8AAAAAAAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAFwMfTDQAwnHigAAAAQAAAAKAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAADGu9p4AAAAAPf0kAAAAAAIAAAAAAAAAAAAAAAAAAAADAAAAAAMKZ4YAAAAAZgfAGgAAAAAAAAABAwpoPAAAAAAAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAABcDH0w0AMJx4oAAAAEAAAACgAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAxrvaeAAAAAD39JAAAAAACAAAAAAAAAAAAAAAAAAAAAwAAAAADCmeGAAAAAGYHwBoAAAAAAAAAAwMKaDwAAAABAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAKikqTmn//////////AAAAAQAAAAEAAAAACKsm8gAAAAAG8R2ZAAAAAAAAAAAAAAABAwpoPAAAAAEAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAAABVVNEQwAAAAA7mRE4Dv6Yi6CokA6xz+RPNm99vpRr7QdyQPf2JN8VxQAAAAqKSpOaf/////////8AAAABAAAAAQAAAAAIqybyAAAAAAbxHZkAAAAAAAAAAAAAAAYAAAADAwpoOwAAAAIAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAAAAWddCcQAAAAFVU0RDAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAAAAAAAAACKk5qAJiWgAAVUckAAAAAAAAAAAAAAAAAAAABAwpoPAAAAAIAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAAAAWddCcQAAAAFVU0RDAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAAAAAAAAACKk5qAJiWgAAVUckAAAAAAAAAAAAAAAAAAAADAwpoPAAAAAAAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAABcDH0w0AMJx4oAAAAEAAAACgAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAxrvaeAAAAAD39JAAAAAACAAAAAAAAAAAAAAAAAAAAAwAAAAADCmeGAAAAAGYHwBoAAAAAAAAAAQMKaDwAAAAAAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAXAx9MNADCceKAAAABAAAAAoAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAMa72ngAAAAA9/SQAAAAAAgAAAAAAAAAAAAAAAAAAAAMAAAAAAwpnhgAAAABmB8AaAAAAAAAAAAMDCmg8AAAAAQAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAAFVU0RDAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAACopKk5p//////////wAAAAEAAAABAAAAAAirJvIAAAAABvEdmQAAAAAAAAAAAAAAAQMKaDwAAAABAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAKikqTmn//////////AAAAAQAAAAEAAAAACKsm8gAAAAAG8R2ZAAAAAAAAAAAAAAAAAAAAAA==\",\n"
            + "  \"fee_meta_xdr\": \"AAAAAgAAAAMDCmg7AAAAAAAAAAD1/FzHjksDwP53T53qZbR7fnocc2HcV0q/mbT9Os86gAAAAAEqutEjAwnHigAAXhMAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAADAAAAAAMKaDsAAAAAZgfENgAAAAAAAAABAwpoPAAAAAAAAAAA9fxcx45LA8D+d0+d6mW0e356HHNh3FdKv5m0/TrPOoAAAAABKrrOAwMJx4oAAF4TAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAwAAAAADCmg7AAAAAGYHxDYAAAAA\",\n"
            + "  \"memo_type\": \"none\",\n"
            + "  \"signatures\": [\n"
            + "    \"kLD9XCzGpJxlpuBr7a6unH/uFBBjIDV3D1p5znEplnD0zIG84UKARjiQ/hrwBk8nnDRqJ4dFAWx6RNnK6n2pDA==\",\n"
            + "    \"BfG3CaWpCdrQwuOBHdxc9xnDMqbXAQobV+MQwaVjR0+kfl+zaNlTyzaOM41hYeJE8u7G6vpKul3qwmrZ7WdTCg==\"\n"
            + "  ],\n"
            + "  \"valid_after\": \"1970-01-01T00:00:00Z\",\n"
            + "  \"preconditions\": {\n"
            + "    \"timebounds\": {\n"
            + "      \"min_time\": \"0\"\n"
            + "    }\n"
            + "  }\n"
            + "}";

    SubmitTransactionResponse submitTransactionResponse =
        GsonSingleton.getInstance().fromJson(json, SubmitTransactionResponse.class);

    assertTrue(submitTransactionResponse.isSuccess());
    assertEquals(
        submitTransactionResponse.getId(),
        "55d0085f71daaf5950895c0a28af0ba0c60a33f5eb6defed06945e435f3bff92");
    assertEquals(submitTransactionResponse.getPagingToken(), "219102138789228544");
    assertTrue(submitTransactionResponse.getSuccessful());
    assertEquals(
        submitTransactionResponse.getHash(),
        "55d0085f71daaf5950895c0a28af0ba0c60a33f5eb6defed06945e435f3bff92");
    assertEquals(submitTransactionResponse.getLedger().longValue(), 51013692);
    assertEquals(submitTransactionResponse.getCreatedAt(), "2024-03-30T07:50:20Z");
    assertEquals(
        submitTransactionResponse.getSourceAccount(),
        "GD27YXGHRZFQHQH6O5HZ32TFWR5X46Q4ONQ5YV2KX6M3J7J2Z45IBCHM");
    assertNull(submitTransactionResponse.getAccountMuxed());
    assertNull(submitTransactionResponse.getAccountMuxedId());
    assertEquals(
        submitTransactionResponse.getSourceAccountSequence().longValue(), 218925452423618068L);
    assertEquals(
        submitTransactionResponse.getFeeAccount(),
        "GD27YXGHRZFQHQH6O5HZ32TFWR5X46Q4ONQ5YV2KX6M3J7J2Z45IBCHM");
    assertNull(submitTransactionResponse.getFeeAccountMuxedId());
    assertEquals(submitTransactionResponse.getFeeCharged().longValue(), 800);
    assertEquals(submitTransactionResponse.getMaxFee().longValue(), 800000);
    assertEquals(submitTransactionResponse.getOperationCount().intValue(), 8);
    assertEquals(
        submitTransactionResponse.getEnvelopeXdr(),
        "AAAAAgAAAAD1/FzHjksDwP53T53qZbR7fnocc2HcV0q/mbT9Os86gAAMNQADCceKAABeFAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAABAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAADAAAAAFVU0RDAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAAAAAAAAADMRusABVTPwCYloAAAAAAWdc06QAAAAEAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAAAMAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAAAAAAAA9/SQIAFVEPAJiWgAAAAABZ10JyAAAAAQAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAAMAAAAAAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAAD39JAAAVVW8AmJaAAAAAAFnXMoYAAAABAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAAwAAAAAAAAABVVNEQwAAAAA7mRE4Dv6Yi6CokA6xz+RPNm99vpRr7QdyQPf2JN8VxQAAAAAPf0kAAAqrFQBMS0AAAAAAWdcyhwAAAAEAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAAADAAAAAAAAAAFVU0RDAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAAAA9/SQAAFVblAJiWgAAAAABZ1zKIAAAAAQAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAAMAAAAAAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAAD39JAAAVV58AmJaAAAAAAFnXNlgAAAABAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAADAAAAAFVU0RDAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAAAAAAAAAPf0j/AAEQ7QAHoSAAAAAAWdc06gAAAAEAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAAAMAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAAAAAAAA9/SQAAFVHJAJiWgAAAAABZ10JxAAAAAAAAAAI6zzqAAAAAQJCw/VwsxqScZabga+2urpx/7hQQYyA1dw9aec5xKZZw9MyBvOFCgEY4kP4a8AZPJ5w0aieHRQFsekTZyup9qQyS2fkeAAAAQAXxtwmlqQna0MLjgR3cXPcZwzKm1wEKG1fjEMGlY0dPpH5fs2jZU8s2jjONYWHiRPLuxur6Srpd6sJq2e1nUwo=");
    assertEquals(
        submitTransactionResponse.getResultXdr(),
        "AAAAAAAAAyAAAAAAAAAACAAAAAAAAAAMAAAAAAAAAAAAAAABAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAAFnXNOkAAAABVVNEQwAAAAA7mRE4Dv6Yi6CokA6xz+RPNm99vpRr7QdyQPf2JN8VxQAAAAAAAAAAAHIyQgCYloAAFVM/AAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAQAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAABZ10JyAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAAAAAAAAIqO4YAmJaAABVRDwAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAEAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAAAAWdcyhgAAAAAAAAABVVNEQwAAAAA7mRE4Dv6Yi6CokA6xz+RPNm99vpRr7QdyQPf2JN8VxQAAAAAPf0kAABVVbwCYloAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAABAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAAFnXMocAAAAAAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAAD39JAAAKqxUATEtAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAQAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAABZ1zKIAAAAAAAAAAFVU0RDAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAAAA9/SQAAFVblAJiWgAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAEAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAAAAWdc2WAAAAAAAAAABVVNEQwAAAAA7mRE4Dv6Yi6CokA6xz+RPNm99vpRr7QdyQPf2JN8VxQAAAAAPf0kAABVXnwCYloAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAABAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAAFnXNOoAAAABVVNEQwAAAAA7mRE4Dv6Yi6CokA6xz+RPNm99vpRr7QdyQPf2JN8VxQAAAAAAAAAAAiphZwAHoSAAARDtAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAQAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAABZ10JxAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAAAAAAAAIqTmoAmJaAABVRyQAAAAAAAAAAAAAAAA==");
    assertEquals(
        submitTransactionResponse.getResultMetaXdr(),
        "AAAAAwAAAAAAAAACAAAAAwMKaDwAAAAAAAAAAPX8XMeOSwPA/ndPnepltHt+ehxzYdxXSr+ZtP06zzqAAAAAASq6zgMDCceKAABeEwAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAMAAAAAAwpoOwAAAABmB8Q2AAAAAAAAAAEDCmg8AAAAAAAAAAD1/FzHjksDwP53T53qZbR7fnocc2HcV0q/mbT9Os86gAAAAAEqus4DAwnHigAAXhQAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAADAAAAAAMKaDwAAAAAZgfEPAAAAAAAAAAIAAAABgAAAAMDCmg7AAAAAgAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAABZ1zTpAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAAAAAAAAByMkIAmJaAABVTPwAAAAAAAAAAAAAAAAAAAAEDCmg8AAAAAgAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAABZ1zTpAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAAAAAAAAByMkIAmJaAABVTPwAAAAAAAAAAAAAAAAAAAAMDCmg7AAAAAAAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAFwMfTDQAwnHigAAAAQAAAAKAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAADGu9p4AAAAAPf0kAAAAAAIAAAAAAAAAAAAAAAAAAAADAAAAAAMKZ4YAAAAAZgfAGgAAAAAAAAABAwpoPAAAAAAAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAABcDH0w0AMJx4oAAAAEAAAACgAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAxrvaeAAAAAD39JAAAAAACAAAAAAAAAAAAAAAAAAAAAwAAAAADCmeGAAAAAGYHwBoAAAAAAAAAAwMKaDsAAAABAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAKikqTmn//////////AAAAAQAAAAEAAAAACKsm8gAAAAAG8R2ZAAAAAAAAAAAAAAABAwpoPAAAAAEAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAAABVVNEQwAAAAA7mRE4Dv6Yi6CokA6xz+RPNm99vpRr7QdyQPf2JN8VxQAAAAqKSpOaf/////////8AAAABAAAAAQAAAAAIqybyAAAAAAbxHZkAAAAAAAAAAAAAAAYAAAADAwpoOwAAAAIAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAAAAWddCcgAAAAFVU0RDAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAAAAAAAAACKjuGAJiWgAAVUQ8AAAAAAAAAAAAAAAAAAAABAwpoPAAAAAIAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAAAAWddCcgAAAAFVU0RDAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAAAAAAAAACKjuGAJiWgAAVUQ8AAAAAAAAAAAAAAAAAAAADAwpoPAAAAAAAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAABcDH0w0AMJx4oAAAAEAAAACgAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAxrvaeAAAAAD39JAAAAAACAAAAAAAAAAAAAAAAAAAAAwAAAAADCmeGAAAAAGYHwBoAAAAAAAAAAQMKaDwAAAAAAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAXAx9MNADCceKAAAABAAAAAoAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAMa72ngAAAAA9/SQAAAAAAgAAAAAAAAAAAAAAAAAAAAMAAAAAAwpnhgAAAABmB8AaAAAAAAAAAAMDCmg8AAAAAQAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAAFVU0RDAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAACopKk5p//////////wAAAAEAAAABAAAAAAirJvIAAAAABvEdmQAAAAAAAAAAAAAAAQMKaDwAAAABAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAKikqTmn//////////AAAAAQAAAAEAAAAACKsm8gAAAAAG8R2ZAAAAAAAAAAAAAAAGAAAAAwMKaDsAAAACAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAAFnXMoYAAAAAAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAAD39JAAAVVW8AmJaAAAAAAAAAAAAAAAAAAAAAAQMKaDwAAAACAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAAFnXMoYAAAAAAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAAD39JAAAVVW8AmJaAAAAAAAAAAAAAAAAAAAAAAwMKaDwAAAABAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAKikqTmn//////////AAAAAQAAAAEAAAAACKsm8gAAAAAG8R2ZAAAAAAAAAAAAAAABAwpoPAAAAAEAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAAABVVNEQwAAAAA7mRE4Dv6Yi6CokA6xz+RPNm99vpRr7QdyQPf2JN8VxQAAAAqKSpOaf/////////8AAAABAAAAAQAAAAAIqybyAAAAAAbxHZkAAAAAAAAAAAAAAAMDCmg8AAAAAAAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAFwMfTDQAwnHigAAAAQAAAAKAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAADGu9p4AAAAAPf0kAAAAAAIAAAAAAAAAAAAAAAAAAAADAAAAAAMKZ4YAAAAAZgfAGgAAAAAAAAABAwpoPAAAAAAAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAABcDH0w0AMJx4oAAAAEAAAACgAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAxrvaeAAAAAD39JAAAAAACAAAAAAAAAAAAAAAAAAAAAwAAAAADCmeGAAAAAGYHwBoAAAAAAAAABgAAAAMDCmg7AAAAAgAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAABZ1zKHAAAAAAAAAAFVU0RDAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAAAA9/SQAACqsVAExLQAAAAAAAAAAAAAAAAAAAAAEDCmg8AAAAAgAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAABZ1zKHAAAAAAAAAAFVU0RDAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAAAA9/SQAACqsVAExLQAAAAAAAAAAAAAAAAAAAAAMDCmg8AAAAAQAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAAFVU0RDAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAACopKk5p//////////wAAAAEAAAABAAAAAAirJvIAAAAABvEdmQAAAAAAAAAAAAAAAQMKaDwAAAABAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAKikqTmn//////////AAAAAQAAAAEAAAAACKsm8gAAAAAG8R2ZAAAAAAAAAAAAAAADAwpoPAAAAAAAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAABcDH0w0AMJx4oAAAAEAAAACgAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAxrvaeAAAAAD39JAAAAAACAAAAAAAAAAAAAAAAAAAAAwAAAAADCmeGAAAAAGYHwBoAAAAAAAAAAQMKaDwAAAAAAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAXAx9MNADCceKAAAABAAAAAoAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAMa72ngAAAAA9/SQAAAAAAgAAAAAAAAAAAAAAAAAAAAMAAAAAAwpnhgAAAABmB8AaAAAAAAAAAAYAAAADAwpoOwAAAAIAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAAAAWdcyiAAAAAAAAAABVVNEQwAAAAA7mRE4Dv6Yi6CokA6xz+RPNm99vpRr7QdyQPf2JN8VxQAAAAAPf0kAABVW5QCYloAAAAAAAAAAAAAAAAAAAAABAwpoPAAAAAIAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAAAAWdcyiAAAAAAAAAABVVNEQwAAAAA7mRE4Dv6Yi6CokA6xz+RPNm99vpRr7QdyQPf2JN8VxQAAAAAPf0kAABVW5QCYloAAAAAAAAAAAAAAAAAAAAADAwpoPAAAAAEAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAAABVVNEQwAAAAA7mRE4Dv6Yi6CokA6xz+RPNm99vpRr7QdyQPf2JN8VxQAAAAqKSpOaf/////////8AAAABAAAAAQAAAAAIqybyAAAAAAbxHZkAAAAAAAAAAAAAAAEDCmg8AAAAAQAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAAFVU0RDAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAACopKk5p//////////wAAAAEAAAABAAAAAAirJvIAAAAABvEdmQAAAAAAAAAAAAAAAwMKaDwAAAAAAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAXAx9MNADCceKAAAABAAAAAoAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAMa72ngAAAAA9/SQAAAAAAgAAAAAAAAAAAAAAAAAAAAMAAAAAAwpnhgAAAABmB8AaAAAAAAAAAAEDCmg8AAAAAAAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAFwMfTDQAwnHigAAAAQAAAAKAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAADGu9p4AAAAAPf0kAAAAAAIAAAAAAAAAAAAAAAAAAAADAAAAAAMKZ4YAAAAAZgfAGgAAAAAAAAAGAAAAAwMKaDsAAAACAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAAFnXNlgAAAAAAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAAD39JAAAVV58AmJaAAAAAAAAAAAAAAAAAAAAAAQMKaDwAAAACAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAAFnXNlgAAAAAAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAAD39JAAAVV58AmJaAAAAAAAAAAAAAAAAAAAAAAwMKaDwAAAABAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAKikqTmn//////////AAAAAQAAAAEAAAAACKsm8gAAAAAG8R2ZAAAAAAAAAAAAAAABAwpoPAAAAAEAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAAABVVNEQwAAAAA7mRE4Dv6Yi6CokA6xz+RPNm99vpRr7QdyQPf2JN8VxQAAAAqKSpOaf/////////8AAAABAAAAAQAAAAAIqybyAAAAAAbxHZkAAAAAAAAAAAAAAAMDCmg8AAAAAAAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAFwMfTDQAwnHigAAAAQAAAAKAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAADGu9p4AAAAAPf0kAAAAAAIAAAAAAAAAAAAAAAAAAAADAAAAAAMKZ4YAAAAAZgfAGgAAAAAAAAABAwpoPAAAAAAAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAABcDH0w0AMJx4oAAAAEAAAACgAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAxrvaeAAAAAD39JAAAAAACAAAAAAAAAAAAAAAAAAAAAwAAAAADCmeGAAAAAGYHwBoAAAAAAAAABgAAAAMDCmg7AAAAAgAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAABZ1zTqAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAAAAAAAAIqYWcAB6EgAAEQ7QAAAAAAAAAAAAAAAAAAAAEDCmg8AAAAAgAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAABZ1zTqAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAAAAAAAAIqYWcAB6EgAAEQ7QAAAAAAAAAAAAAAAAAAAAMDCmg8AAAAAAAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAFwMfTDQAwnHigAAAAQAAAAKAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAADGu9p4AAAAAPf0kAAAAAAIAAAAAAAAAAAAAAAAAAAADAAAAAAMKZ4YAAAAAZgfAGgAAAAAAAAABAwpoPAAAAAAAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAABcDH0w0AMJx4oAAAAEAAAACgAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAxrvaeAAAAAD39JAAAAAACAAAAAAAAAAAAAAAAAAAAAwAAAAADCmeGAAAAAGYHwBoAAAAAAAAAAwMKaDwAAAABAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAKikqTmn//////////AAAAAQAAAAEAAAAACKsm8gAAAAAG8R2ZAAAAAAAAAAAAAAABAwpoPAAAAAEAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAAABVVNEQwAAAAA7mRE4Dv6Yi6CokA6xz+RPNm99vpRr7QdyQPf2JN8VxQAAAAqKSpOaf/////////8AAAABAAAAAQAAAAAIqybyAAAAAAbxHZkAAAAAAAAAAAAAAAYAAAADAwpoOwAAAAIAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAAAAWddCcQAAAAFVU0RDAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAAAAAAAAACKk5qAJiWgAAVUckAAAAAAAAAAAAAAAAAAAABAwpoPAAAAAIAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAAAAWddCcQAAAAFVU0RDAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAAAAAAAAACKk5qAJiWgAAVUckAAAAAAAAAAAAAAAAAAAADAwpoPAAAAAAAAAAAP9udEr07DsLzWMTotTSavPIdf1C+e0HzjB/0d5LZ+R4AAABcDH0w0AMJx4oAAAAEAAAACgAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAxrvaeAAAAAD39JAAAAAACAAAAAAAAAAAAAAAAAAAAAwAAAAADCmeGAAAAAGYHwBoAAAAAAAAAAQMKaDwAAAAAAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAXAx9MNADCceKAAAABAAAAAoAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAMa72ngAAAAA9/SQAAAAAAgAAAAAAAAAAAAAAAAAAAAMAAAAAAwpnhgAAAABmB8AaAAAAAAAAAAMDCmg8AAAAAQAAAAA/250SvTsOwvNYxOi1NJq88h1/UL57QfOMH/R3ktn5HgAAAAFVU0RDAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAACopKk5p//////////wAAAAEAAAABAAAAAAirJvIAAAAABvEdmQAAAAAAAAAAAAAAAQMKaDwAAAABAAAAAD/bnRK9Ow7C81jE6LU0mrzyHX9QvntB84wf9HeS2fkeAAAAAVVTREMAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAKikqTmn//////////AAAAAQAAAAEAAAAACKsm8gAAAAAG8R2ZAAAAAAAAAAAAAAAAAAAAAA==");
    assertEquals(
        submitTransactionResponse.getFeeMetaXdr(),
        "AAAAAgAAAAMDCmg7AAAAAAAAAAD1/FzHjksDwP53T53qZbR7fnocc2HcV0q/mbT9Os86gAAAAAEqutEjAwnHigAAXhMAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAADAAAAAAMKaDsAAAAAZgfENgAAAAAAAAABAwpoPAAAAAAAAAAA9fxcx45LA8D+d0+d6mW0e356HHNh3FdKv5m0/TrPOoAAAAABKrrOAwMJx4oAAF4TAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAwAAAAADCmg7AAAAAGYHxDYAAAAA");
    assertEquals(submitTransactionResponse.getMemo(), Memo.none());
    assertTrue(submitTransactionResponse.getPreconditions().isPresent());
    assertEquals(
        submitTransactionResponse.getPreconditions().get().getTimeBounds().getMinTime(), 0);
    assertEquals(
        submitTransactionResponse.getPreconditions().get().getTimeBounds().getMaxTime(), 0);
    assertEquals(
        submitTransactionResponse.getSignatures().get(0),
        "kLD9XCzGpJxlpuBr7a6unH/uFBBjIDV3D1p5znEplnD0zIG84UKARjiQ/hrwBk8nnDRqJ4dFAWx6RNnK6n2pDA==");
    assertEquals(
        submitTransactionResponse.getSignatures().get(1),
        "BfG3CaWpCdrQwuOBHdxc9xnDMqbXAQobV+MQwaVjR0+kfl+zaNlTyzaOM41hYeJE8u7G6vpKul3qwmrZ7WdTCg==");
    assertNull(submitTransactionResponse.getFeeBumpTransaction());
    assertNull(submitTransactionResponse.getInnerTransaction());
    assertEquals(
        submitTransactionResponse.getLinks().getAccount().getHref(),
        "https://horizon.stellar.org/accounts/GD27YXGHRZFQHQH6O5HZ32TFWR5X46Q4ONQ5YV2KX6M3J7J2Z45IBCHM");
    assertTrue(submitTransactionResponse.isSuccess());
    assertEquals(submitTransactionResponse.getOfferIdFromResult(1).get().longValue(), 1507279474);
    TransactionResult transactionResult =
        submitTransactionResponse.getDecodedTransactionResult().get();
    assertEquals(transactionResult.getResult().getDiscriminant(), TransactionResultCode.txSUCCESS);
    assertEquals(transactionResult.getResult().getResults().length, 8);
    assertEquals(
        transactionResult.getResult().getResults()[0].getTr().getDiscriminant(),
        OperationType.MANAGE_BUY_OFFER);
    assertNotNull(transactionResult.getResult().getResults()[0].getTr().getManageBuyOfferResult());
  }

  @Test
  public void testDeserializeNoOfferID() throws IOException {
    String json =
        "{\n"
            + "  \"memo\": \"hello\",\n"
            + "  \"memo_bytes\": \"aGVsbG8=\",\n"
            + "  \"_links\": {\n"
            + "    \"self\": {\n"
            + "      \"href\": \"https://horizon-testnet.stellar.org/transactions/fb7645c000252b9ba78dc53b3bca99fc21c47b6cf77bf0861b13ed139046af63\"\n"
            + "    },\n"
            + "    \"account\": {\n"
            + "      \"href\": \"https://horizon-testnet.stellar.org/accounts/GDCMOZCUKMGVV4QC6EGS2PMZWY2SODZ5G6QBJUG7MJXX4AT7OJGVALJE\"\n"
            + "    },\n"
            + "    \"ledger\": { \"href\": \"https://horizon-testnet.stellar.org/ledgers/864774\" },\n"
            + "    \"operations\": {\n"
            + "      \"href\": \"https://horizon-testnet.stellar.org/transactions/fb7645c000252b9ba78dc53b3bca99fc21c47b6cf77bf0861b13ed139046af63/operations{?cursor,limit,order}\",\n"
            + "      \"templated\": true\n"
            + "    },\n"
            + "    \"effects\": {\n"
            + "      \"href\": \"https://horizon-testnet.stellar.org/transactions/fb7645c000252b9ba78dc53b3bca99fc21c47b6cf77bf0861b13ed139046af63/effects{?cursor,limit,order}\",\n"
            + "      \"templated\": true\n"
            + "    },\n"
            + "    \"precedes\": {\n"
            + "      \"href\": \"https://horizon-testnet.stellar.org/transactions?order=asc&cursor=3714176048435200\"\n"
            + "    },\n"
            + "    \"succeeds\": {\n"
            + "      \"href\": \"https://horizon-testnet.stellar.org/transactions?order=desc&cursor=3714176048435200\"\n"
            + "    },\n"
            + "    \"transaction\": {\n"
            + "      \"href\": \"https://horizon-testnet.stellar.org/transactions/fb7645c000252b9ba78dc53b3bca99fc21c47b6cf77bf0861b13ed139046af63\"\n"
            + "    }\n"
            + "  },\n"
            + "  \"id\": \"fb7645c000252b9ba78dc53b3bca99fc21c47b6cf77bf0861b13ed139046af63\",\n"
            + "  \"paging_token\": \"3714176048435200\",\n"
            + "  \"successful\": true,\n"
            + "  \"hash\": \"fb7645c000252b9ba78dc53b3bca99fc21c47b6cf77bf0861b13ed139046af63\",\n"
            + "  \"ledger\": 864774,\n"
            + "  \"created_at\": \"2024-03-30T07:59:05Z\",\n"
            + "  \"source_account\": \"GDCMOZCUKMGVV4QC6EGS2PMZWY2SODZ5G6QBJUG7MJXX4AT7OJGVALJE\",\n"
            + "  \"source_account_sequence\": \"3712926212947971\",\n"
            + "  \"fee_account\": \"GDCMOZCUKMGVV4QC6EGS2PMZWY2SODZ5G6QBJUG7MJXX4AT7OJGVALJE\",\n"
            + "  \"fee_charged\": \"100\",\n"
            + "  \"max_fee\": \"100\",\n"
            + "  \"operation_count\": 1,\n"
            + "  \"envelope_xdr\": \"AAAAAgAAAADEx2RUUw1a8gLxDS09mbY1Jw89N6AU0N9ib34Cf3JNUAAAAGQADTDjAAAAAwAAAAEAAAAAAAAAAAAAAABmB8arAAAAAQAAAAVoZWxsbwAAAAAAAAEAAAAAAAAAAQAAAADbJaZi5NHkrFrlT++qNZGIaNyBvE8ClqDUtjN9X0SMMgAAAAAAAAAAO5rKAAAAAAAAAAABf3JNUAAAAED3nY2+qv/7khWLstMqEuSRhLNiSBAHUOdsrM03qZmPpte72j6HCRCk2Qa+KswHDs8C0PnqGYpUxe4IdKob50wG\",\n"
            + "  \"result_xdr\": \"AAAAAAAAAGQAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAA=\",\n"
            + "  \"result_meta_xdr\": \"AAAAAwAAAAAAAAACAAAAAwANMgYAAAAAAAAAAMTHZFRTDVryAvENLT2ZtjUnDz03oBTQ32JvfgJ/ck1QAAAAFwzcHNQADTDjAAAAAgAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAMAAAAAAA0xHAAAAABmB8F5AAAAAAAAAAEADTIGAAAAAAAAAADEx2RUUw1a8gLxDS09mbY1Jw89N6AU0N9ib34Cf3JNUAAAABcM3BzUAA0w4wAAAAMAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAADAAAAAAANMgYAAAAAZgfGSQAAAAAAAAABAAAABAAAAAMADTIGAAAAAAAAAADEx2RUUw1a8gLxDS09mbY1Jw89N6AU0N9ib34Cf3JNUAAAABcM3BzUAA0w4wAAAAMAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAADAAAAAAANMgYAAAAAZgfGSQAAAAAAAAABAA0yBgAAAAAAAAAAxMdkVFMNWvIC8Q0tPZm2NScPPTegFNDfYm9+An9yTVAAAAAW0UFS1AANMOMAAAADAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAwAAAAAADTIGAAAAAGYHxkkAAAAAAAAAAwANMRwAAAAAAAAAANslpmLk0eSsWuVP76o1kYho3IG8TwKWoNS2M31fRIwyAAAAF4QRsgAADTEYAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAQANMgYAAAAAAAAAANslpmLk0eSsWuVP76o1kYho3IG8TwKWoNS2M31fRIwyAAAAF7+sfAAADTEYAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=\",\n"
            + "  \"fee_meta_xdr\": \"AAAAAgAAAAMADTEcAAAAAAAAAADEx2RUUw1a8gLxDS09mbY1Jw89N6AU0N9ib34Cf3JNUAAAABcM3B04AA0w4wAAAAIAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAADAAAAAAANMRwAAAAAZgfBeQAAAAAAAAABAA0yBgAAAAAAAAAAxMdkVFMNWvIC8Q0tPZm2NScPPTegFNDfYm9+An9yTVAAAAAXDNwc1AANMOMAAAACAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAwAAAAAADTEcAAAAAGYHwXkAAAAA\",\n"
            + "  \"memo_type\": \"text\",\n"
            + "  \"signatures\": [\n"
            + "    \"952Nvqr/+5IVi7LTKhLkkYSzYkgQB1DnbKzNN6mZj6bXu9o+hwkQpNkGvirMBw7PAtD56hmKVMXuCHSqG+dMBg==\"\n"
            + "  ],\n"
            + "  \"valid_after\": \"1970-01-01T00:00:00Z\",\n"
            + "  \"valid_before\": \"2024-03-30T08:00:43Z\",\n"
            + "  \"preconditions\": {\n"
            + "    \"timebounds\": { \"min_time\": \"0\", \"max_time\": \"1711785643\" }\n"
            + "  }\n"
            + "}";

    SubmitTransactionResponse submitTransactionResponse =
        GsonSingleton.getInstance().fromJson(json, SubmitTransactionResponse.class);
    assertTrue(submitTransactionResponse.isSuccess());
    assertEquals(
        submitTransactionResponse.getId(),
        "fb7645c000252b9ba78dc53b3bca99fc21c47b6cf77bf0861b13ed139046af63");
    assertEquals(submitTransactionResponse.getPagingToken(), "3714176048435200");
    assertTrue(submitTransactionResponse.getSuccessful());
    assertEquals(
        submitTransactionResponse.getHash(),
        "fb7645c000252b9ba78dc53b3bca99fc21c47b6cf77bf0861b13ed139046af63");
    assertEquals(submitTransactionResponse.getLedger().longValue(), 864774);
    assertEquals(submitTransactionResponse.getCreatedAt(), "2024-03-30T07:59:05Z");
    assertEquals(
        submitTransactionResponse.getSourceAccount(),
        "GDCMOZCUKMGVV4QC6EGS2PMZWY2SODZ5G6QBJUG7MJXX4AT7OJGVALJE");
    assertNull(submitTransactionResponse.getAccountMuxed());
    assertNull(submitTransactionResponse.getAccountMuxedId());
    assertEquals(
        submitTransactionResponse.getSourceAccountSequence().longValue(), 3712926212947971L);
    assertEquals(
        submitTransactionResponse.getFeeAccount(),
        "GDCMOZCUKMGVV4QC6EGS2PMZWY2SODZ5G6QBJUG7MJXX4AT7OJGVALJE");
    assertNull(submitTransactionResponse.getFeeAccountMuxedId());
    assertEquals(submitTransactionResponse.getFeeCharged().longValue(), 100);
    assertEquals(submitTransactionResponse.getMaxFee().longValue(), 100);
    assertEquals(submitTransactionResponse.getOperationCount().intValue(), 1);
    assertEquals(
        submitTransactionResponse.getEnvelopeXdr(),
        "AAAAAgAAAADEx2RUUw1a8gLxDS09mbY1Jw89N6AU0N9ib34Cf3JNUAAAAGQADTDjAAAAAwAAAAEAAAAAAAAAAAAAAABmB8arAAAAAQAAAAVoZWxsbwAAAAAAAAEAAAAAAAAAAQAAAADbJaZi5NHkrFrlT++qNZGIaNyBvE8ClqDUtjN9X0SMMgAAAAAAAAAAO5rKAAAAAAAAAAABf3JNUAAAAED3nY2+qv/7khWLstMqEuSRhLNiSBAHUOdsrM03qZmPpte72j6HCRCk2Qa+KswHDs8C0PnqGYpUxe4IdKob50wG");
    assertEquals(
        submitTransactionResponse.getResultXdr(), "AAAAAAAAAGQAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAA=");
    assertEquals(
        submitTransactionResponse.getResultMetaXdr(),
        "AAAAAwAAAAAAAAACAAAAAwANMgYAAAAAAAAAAMTHZFRTDVryAvENLT2ZtjUnDz03oBTQ32JvfgJ/ck1QAAAAFwzcHNQADTDjAAAAAgAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAMAAAAAAA0xHAAAAABmB8F5AAAAAAAAAAEADTIGAAAAAAAAAADEx2RUUw1a8gLxDS09mbY1Jw89N6AU0N9ib34Cf3JNUAAAABcM3BzUAA0w4wAAAAMAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAADAAAAAAANMgYAAAAAZgfGSQAAAAAAAAABAAAABAAAAAMADTIGAAAAAAAAAADEx2RUUw1a8gLxDS09mbY1Jw89N6AU0N9ib34Cf3JNUAAAABcM3BzUAA0w4wAAAAMAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAADAAAAAAANMgYAAAAAZgfGSQAAAAAAAAABAA0yBgAAAAAAAAAAxMdkVFMNWvIC8Q0tPZm2NScPPTegFNDfYm9+An9yTVAAAAAW0UFS1AANMOMAAAADAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAwAAAAAADTIGAAAAAGYHxkkAAAAAAAAAAwANMRwAAAAAAAAAANslpmLk0eSsWuVP76o1kYho3IG8TwKWoNS2M31fRIwyAAAAF4QRsgAADTEYAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAQANMgYAAAAAAAAAANslpmLk0eSsWuVP76o1kYho3IG8TwKWoNS2M31fRIwyAAAAF7+sfAAADTEYAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=");
    assertEquals(
        submitTransactionResponse.getFeeMetaXdr(),
        "AAAAAgAAAAMADTEcAAAAAAAAAADEx2RUUw1a8gLxDS09mbY1Jw89N6AU0N9ib34Cf3JNUAAAABcM3B04AA0w4wAAAAIAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAADAAAAAAANMRwAAAAAZgfBeQAAAAAAAAABAA0yBgAAAAAAAAAAxMdkVFMNWvIC8Q0tPZm2NScPPTegFNDfYm9+An9yTVAAAAAXDNwc1AANMOMAAAACAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAwAAAAAADTEcAAAAAGYHwXkAAAAA");
    assertEquals(submitTransactionResponse.getMemo(), Memo.text("hello"));
    assertEquals(submitTransactionResponse.getSignatures().size(), 1);
    assertEquals(
        submitTransactionResponse.getSignatures().get(0),
        "952Nvqr/+5IVi7LTKhLkkYSzYkgQB1DnbKzNN6mZj6bXu9o+hwkQpNkGvirMBw7PAtD56hmKVMXuCHSqG+dMBg==");
    assertTrue(submitTransactionResponse.getPreconditions().isPresent());
    assertEquals(
        submitTransactionResponse.getPreconditions().get().getTimeBounds().getMinTime(), 0);
    assertEquals(
        submitTransactionResponse.getPreconditions().get().getTimeBounds().getMaxTime(),
        1711785643);
    assertNull(submitTransactionResponse.getFeeBumpTransaction());
    assertNull(submitTransactionResponse.getInnerTransaction());
    assertEquals(
        submitTransactionResponse.getLinks().getAccount().getHref(),
        "https://horizon-testnet.stellar.org/accounts/GDCMOZCUKMGVV4QC6EGS2PMZWY2SODZ5G6QBJUG7MJXX4AT7OJGVALJE");
    assertTrue(submitTransactionResponse.isSuccess());
    assertFalse(submitTransactionResponse.getOfferIdFromResult(0).isPresent());
    assertTrue(submitTransactionResponse.getDecodedTransactionResult().isPresent());
  }
}
