// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;

import java.io.IOException;

import org.stellar.sdk.Base64Factory;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.List;
import java.util.ArrayList;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.Builder;

/**
 * MyUnion's original definition in the XDR file is:
 * <pre>
 * union MyUnion switch (UnionKey type)
 * {
 *     case ONE:
 *         struct {
 *             int someInt;
 *         } one;
 * 
 *     case TWO:
 *         struct {
 *             int someInt;
 *             Foo foo;
 *         } two;
 * 
 *     case OFFER:
 *         void;
 * };
 * </pre>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
public class MyUnion implements XdrElement {
  private UnionKey discriminant;
  private MyUnionOne one;
  private MyUnionTwo two;

  public void encode(XdrDataOutputStream stream) throws IOException {
  stream.writeInt(discriminant.getValue());
  switch (discriminant) {
  case ONE:
  one.encode(stream);
  break;
  case TWO:
  two.encode(stream);
  break;
  case OFFER:
  break;
  }
  }
  public static MyUnion decode(XdrDataInputStream stream, int maxDepth) throws IOException {
  if (maxDepth <= 0) {
    throw new IOException("Maximum decoding depth reached");
  }
  maxDepth -= 1;
  MyUnion decodedMyUnion = new MyUnion();
  UnionKey discriminant = UnionKey.decode(stream, maxDepth);
  decodedMyUnion.setDiscriminant(discriminant);
  switch (decodedMyUnion.getDiscriminant()) {
  case ONE:
  decodedMyUnion.one = MyUnionOne.decode(stream, maxDepth);
  break;
  case TWO:
  decodedMyUnion.two = MyUnionTwo.decode(stream, maxDepth);
  break;
  case OFFER:
  break;
  default:
    throw new IOException("Unknown discriminant value: " + discriminant);
  }
    return decodedMyUnion;
  }
  public static MyUnion decode(XdrDataInputStream stream) throws IOException {
    return decode(stream, XdrDataInputStream.DEFAULT_MAX_DEPTH);
  }
  public static MyUnion fromXdrBase64(String xdr) throws IOException {
    byte[] bytes = Base64Factory.getInstance().decode(xdr);
    return fromXdrByteArray(bytes);
  }

  public static MyUnion fromXdrByteArray(byte[] xdr) throws IOException {
    ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
    XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
    xdrDataInputStream.setMaxInputLen(xdr.length);
    return decode(xdrDataInputStream);
  }
  @Override
  public String toJson() {
    return XdrElement.gson.toJson(toJsonObject());
  }

  public static MyUnion fromJson(String json) {
    return fromJsonObject(XdrElement.gson.fromJson(json, Object.class));
  }
  Object toJsonObject() {
    if (discriminant == UnionKey.ONE) {
      LinkedHashMap<String, Object> jsonMap = new LinkedHashMap<>();
      jsonMap.put("one", one.toJsonObject());
      return jsonMap;
    }
    if (discriminant == UnionKey.TWO) {
      LinkedHashMap<String, Object> jsonMap = new LinkedHashMap<>();
      jsonMap.put("two", two.toJsonObject());
      return jsonMap;
    }
    if (discriminant == UnionKey.OFFER) {
      return "offer";
    }
    throw new IllegalArgumentException("Unknown discriminant: " + discriminant);
  }
  @SuppressWarnings("unchecked")
  static MyUnion fromJsonObject(Object json) {
    if (json instanceof String) {
      String strVal = (String) json;
      if (!(strVal.equals("offer"))) {
        throw new IllegalArgumentException("Unexpected string '" + strVal + "' for MyUnion");
      }
      MyUnion instance = new MyUnion();
      instance.discriminant = UnionKey.fromJsonObject(strVal);
      return instance;
    }
    java.util.Map<String, Object> jsonMap = (java.util.Map<String, Object>) json;
    if (jsonMap.containsKey("$schema")) {
      jsonMap = new LinkedHashMap<>(jsonMap);
      jsonMap.remove("$schema");
    }
    if (jsonMap.size() != 1) {
      throw new IllegalArgumentException("Expected a single-key object for MyUnion, got: " + json);
    }
    String key = jsonMap.keySet().iterator().next();
    UnionKey discriminant = UnionKey.fromJsonObject(key);
    if (key.equals("one")) {
      MyUnion instance = new MyUnion();
      instance.discriminant = discriminant;
      instance.one = MyUnionOne.fromJsonObject(jsonMap.get("one"));
      return instance;
    }
    if (key.equals("two")) {
      MyUnion instance = new MyUnion();
      instance.discriminant = discriminant;
      instance.two = MyUnionTwo.fromJsonObject(jsonMap.get("two"));
      return instance;
    }
    throw new IllegalArgumentException("Unknown key '" + key + "' for MyUnion");
  }

  /**
   * MyUnionOne's original definition in the XDR file is:
   * <pre>
   * struct {
   *             int someInt;
   *         }
   * </pre>
   */
  @Data
  @NoArgsConstructor
  @AllArgsConstructor
  @Builder(toBuilder = true)
  public static class MyUnionOne implements XdrElement {
    private Integer someInt;
    public void encode(XdrDataOutputStream stream) throws IOException{
      stream.writeInt(someInt);
    }
    public static MyUnionOne decode(XdrDataInputStream stream, int maxDepth) throws IOException {
      if (maxDepth <= 0) {
        throw new IOException("Maximum decoding depth reached");
      }
      maxDepth -= 1;
      MyUnionOne decodedMyUnionOne = new MyUnionOne();
      decodedMyUnionOne.someInt = stream.readInt();
      return decodedMyUnionOne;
    }
    public static MyUnionOne decode(XdrDataInputStream stream) throws IOException {
      return decode(stream, XdrDataInputStream.DEFAULT_MAX_DEPTH);
    }
    public static MyUnionOne fromXdrBase64(String xdr) throws IOException {
      byte[] bytes = Base64Factory.getInstance().decode(xdr);
      return fromXdrByteArray(bytes);
    }

    public static MyUnionOne fromXdrByteArray(byte[] xdr) throws IOException {
      ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
      XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
      xdrDataInputStream.setMaxInputLen(xdr.length);
      return decode(xdrDataInputStream);
    }
    @Override
    public String toJson() {
      return XdrElement.gson.toJson(toJsonObject());
    }

    public static MyUnionOne fromJson(String json) {
      return fromJsonObject(XdrElement.gson.fromJson(json, Object.class));
    }
    Object toJsonObject() {
      LinkedHashMap<String, Object> jsonMap = new LinkedHashMap<>();
      jsonMap.put("some_int", (Integer) someInt);
      return jsonMap;
    }
    @SuppressWarnings("unchecked")
    static MyUnionOne fromJsonObject(Object json) {
      java.util.Map<String, Object> jsonMap = (java.util.Map<String, Object>) json;
      MyUnionOne instance = new MyUnionOne();
      instance.someInt = ((Number) jsonMap.get("some_int")).intValue();
      return instance;
    }

  }
  /**
   * MyUnionTwo's original definition in the XDR file is:
   * <pre>
   * struct {
   *             int someInt;
   *             Foo foo;
   *         }
   * </pre>
   */
  @Data
  @NoArgsConstructor
  @AllArgsConstructor
  @Builder(toBuilder = true)
  public static class MyUnionTwo implements XdrElement {
    private Integer someInt;
    private Foo foo;
    public void encode(XdrDataOutputStream stream) throws IOException{
      stream.writeInt(someInt);
      foo.encode(stream);
    }
    public static MyUnionTwo decode(XdrDataInputStream stream, int maxDepth) throws IOException {
      if (maxDepth <= 0) {
        throw new IOException("Maximum decoding depth reached");
      }
      maxDepth -= 1;
      MyUnionTwo decodedMyUnionTwo = new MyUnionTwo();
      decodedMyUnionTwo.someInt = stream.readInt();
      decodedMyUnionTwo.foo = Foo.decode(stream, maxDepth);
      return decodedMyUnionTwo;
    }
    public static MyUnionTwo decode(XdrDataInputStream stream) throws IOException {
      return decode(stream, XdrDataInputStream.DEFAULT_MAX_DEPTH);
    }
    public static MyUnionTwo fromXdrBase64(String xdr) throws IOException {
      byte[] bytes = Base64Factory.getInstance().decode(xdr);
      return fromXdrByteArray(bytes);
    }

    public static MyUnionTwo fromXdrByteArray(byte[] xdr) throws IOException {
      ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
      XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
      xdrDataInputStream.setMaxInputLen(xdr.length);
      return decode(xdrDataInputStream);
    }
    @Override
    public String toJson() {
      return XdrElement.gson.toJson(toJsonObject());
    }

    public static MyUnionTwo fromJson(String json) {
      return fromJsonObject(XdrElement.gson.fromJson(json, Object.class));
    }
    Object toJsonObject() {
      LinkedHashMap<String, Object> jsonMap = new LinkedHashMap<>();
      jsonMap.put("some_int", (Integer) someInt);
      jsonMap.put("foo", foo.toJsonObject());
      return jsonMap;
    }
    @SuppressWarnings("unchecked")
    static MyUnionTwo fromJsonObject(Object json) {
      java.util.Map<String, Object> jsonMap = (java.util.Map<String, Object>) json;
      MyUnionTwo instance = new MyUnionTwo();
      instance.someInt = ((Number) jsonMap.get("some_int")).intValue();
      instance.foo = Foo.fromJsonObject(jsonMap.get("foo"));
      return instance;
    }

  }
}
