// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.stellar.sdk.Base64Factory;

/**
 * AllowTrustResult's original definition in the XDR file is:
 *
 * <pre>
 * union AllowTrustResult switch (AllowTrustResultCode code)
 * {
 * case ALLOW_TRUST_SUCCESS:
 *     void;
 * case ALLOW_TRUST_MALFORMED:
 * case ALLOW_TRUST_NO_TRUST_LINE:
 * case ALLOW_TRUST_TRUST_NOT_REQUIRED:
 * case ALLOW_TRUST_CANT_REVOKE:
 * case ALLOW_TRUST_SELF_NOT_ALLOWED:
 * case ALLOW_TRUST_LOW_RESERVE:
 *     void;
 * };
 * </pre>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
public class AllowTrustResult implements XdrElement {
  private AllowTrustResultCode discriminant;

  public void encode(XdrDataOutputStream stream) throws IOException {
    stream.writeInt(discriminant.getValue());
    switch (discriminant) {
      case ALLOW_TRUST_SUCCESS:
        break;
      case ALLOW_TRUST_MALFORMED:
      case ALLOW_TRUST_NO_TRUST_LINE:
      case ALLOW_TRUST_TRUST_NOT_REQUIRED:
      case ALLOW_TRUST_CANT_REVOKE:
      case ALLOW_TRUST_SELF_NOT_ALLOWED:
      case ALLOW_TRUST_LOW_RESERVE:
        break;
    }
  }

  public static AllowTrustResult decode(XdrDataInputStream stream, int maxDepth)
      throws IOException {
    if (maxDepth <= 0) {
      throw new IOException("Maximum decoding depth reached");
    }
    maxDepth -= 1;
    AllowTrustResult decodedAllowTrustResult = new AllowTrustResult();
    AllowTrustResultCode discriminant = AllowTrustResultCode.decode(stream, maxDepth);
    decodedAllowTrustResult.setDiscriminant(discriminant);
    switch (decodedAllowTrustResult.getDiscriminant()) {
      case ALLOW_TRUST_SUCCESS:
        break;
      case ALLOW_TRUST_MALFORMED:
      case ALLOW_TRUST_NO_TRUST_LINE:
      case ALLOW_TRUST_TRUST_NOT_REQUIRED:
      case ALLOW_TRUST_CANT_REVOKE:
      case ALLOW_TRUST_SELF_NOT_ALLOWED:
      case ALLOW_TRUST_LOW_RESERVE:
        break;
      default:
        throw new IOException("Unknown discriminant value: " + discriminant);
    }
    return decodedAllowTrustResult;
  }

  public static AllowTrustResult decode(XdrDataInputStream stream) throws IOException {
    return decode(stream, XdrDataInputStream.DEFAULT_MAX_DEPTH);
  }

  public static AllowTrustResult fromXdrBase64(String xdr) throws IOException {
    byte[] bytes = Base64Factory.getInstance().decode(xdr);
    return fromXdrByteArray(bytes);
  }

  public static AllowTrustResult fromXdrByteArray(byte[] xdr) throws IOException {
    ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
    XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
    xdrDataInputStream.setMaxInputLen(xdr.length);
    return decode(xdrDataInputStream);
  }

  @Override
  public String toJson() {
    return XdrElement.gson.toJson(toJsonObject());
  }

  public static AllowTrustResult fromJson(String json) {
    return fromJsonObject(XdrElement.gson.fromJson(json, Object.class));
  }

  Object toJsonObject() {
    if (discriminant == AllowTrustResultCode.ALLOW_TRUST_SUCCESS) {
      return "success";
    }
    if (discriminant == AllowTrustResultCode.ALLOW_TRUST_MALFORMED) {
      return "malformed";
    }
    if (discriminant == AllowTrustResultCode.ALLOW_TRUST_NO_TRUST_LINE) {
      return "no_trust_line";
    }
    if (discriminant == AllowTrustResultCode.ALLOW_TRUST_TRUST_NOT_REQUIRED) {
      return "trust_not_required";
    }
    if (discriminant == AllowTrustResultCode.ALLOW_TRUST_CANT_REVOKE) {
      return "cant_revoke";
    }
    if (discriminant == AllowTrustResultCode.ALLOW_TRUST_SELF_NOT_ALLOWED) {
      return "self_not_allowed";
    }
    if (discriminant == AllowTrustResultCode.ALLOW_TRUST_LOW_RESERVE) {
      return "low_reserve";
    }
    throw new IllegalArgumentException("Unknown discriminant: " + discriminant);
  }

  @SuppressWarnings("unchecked")
  static AllowTrustResult fromJsonObject(Object json) {
    if (json instanceof String) {
      String strVal = (String) json;
      if (!(strVal.equals("success")
          || strVal.equals("malformed")
          || strVal.equals("no_trust_line")
          || strVal.equals("trust_not_required")
          || strVal.equals("cant_revoke")
          || strVal.equals("self_not_allowed")
          || strVal.equals("low_reserve"))) {
        throw new IllegalArgumentException(
            "Unexpected string '" + strVal + "' for AllowTrustResult");
      }
      AllowTrustResult instance = new AllowTrustResult();
      instance.discriminant = AllowTrustResultCode.fromJsonObject(strVal);
      return instance;
    }
    throw new IllegalArgumentException("Expected a string for AllowTrustResult, got: " + json);
  }
}
