// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;

import static org.stellar.sdk.xdr.Constants.*;

import com.google.common.base.Objects;
import java.io.IOException;

// === xdr source ============================================================

//  struct BumpFootprintExpirationOp
//  {
//      ExtensionPoint ext;
//      uint32 ledgersToExpire;
//  };

//  ===========================================================================
public class BumpFootprintExpirationOp implements XdrElement {
  public BumpFootprintExpirationOp() {}

  private ExtensionPoint ext;

  public ExtensionPoint getExt() {
    return this.ext;
  }

  public void setExt(ExtensionPoint value) {
    this.ext = value;
  }

  private Uint32 ledgersToExpire;

  public Uint32 getLedgersToExpire() {
    return this.ledgersToExpire;
  }

  public void setLedgersToExpire(Uint32 value) {
    this.ledgersToExpire = value;
  }

  public static void encode(
      XdrDataOutputStream stream, BumpFootprintExpirationOp encodedBumpFootprintExpirationOp)
      throws IOException {
    ExtensionPoint.encode(stream, encodedBumpFootprintExpirationOp.ext);
    Uint32.encode(stream, encodedBumpFootprintExpirationOp.ledgersToExpire);
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }

  public static BumpFootprintExpirationOp decode(XdrDataInputStream stream) throws IOException {
    BumpFootprintExpirationOp decodedBumpFootprintExpirationOp = new BumpFootprintExpirationOp();
    decodedBumpFootprintExpirationOp.ext = ExtensionPoint.decode(stream);
    decodedBumpFootprintExpirationOp.ledgersToExpire = Uint32.decode(stream);
    return decodedBumpFootprintExpirationOp;
  }

  @Override
  public int hashCode() {
    return Objects.hashCode(this.ext, this.ledgersToExpire);
  }

  @Override
  public boolean equals(Object object) {
    if (!(object instanceof BumpFootprintExpirationOp)) {
      return false;
    }

    BumpFootprintExpirationOp other = (BumpFootprintExpirationOp) object;
    return Objects.equal(this.ext, other.ext)
        && Objects.equal(this.ledgersToExpire, other.ledgersToExpire);
  }

  public static final class Builder {
    private ExtensionPoint ext;
    private Uint32 ledgersToExpire;

    public Builder ext(ExtensionPoint ext) {
      this.ext = ext;
      return this;
    }

    public Builder ledgersToExpire(Uint32 ledgersToExpire) {
      this.ledgersToExpire = ledgersToExpire;
      return this;
    }

    public BumpFootprintExpirationOp build() {
      BumpFootprintExpirationOp val = new BumpFootprintExpirationOp();
      val.setExt(this.ext);
      val.setLedgersToExpire(this.ledgersToExpire);
      return val;
    }
  }
}
