// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import org.stellar.sdk.Base64Factory;

/**
 * ClaimAtomType's original definition in the XDR file is:
 *
 * <pre>
 * enum ClaimAtomType
 * {
 *     CLAIM_ATOM_TYPE_V0 = 0,
 *     CLAIM_ATOM_TYPE_ORDER_BOOK = 1,
 *     CLAIM_ATOM_TYPE_LIQUIDITY_POOL = 2
 * };
 * </pre>
 */
public enum ClaimAtomType implements XdrElement {
  CLAIM_ATOM_TYPE_V0(0),
  CLAIM_ATOM_TYPE_ORDER_BOOK(1),
  CLAIM_ATOM_TYPE_LIQUIDITY_POOL(2);

  private final int value;

  ClaimAtomType(int value) {
    this.value = value;
  }

  public int getValue() {
    return value;
  }

  public static ClaimAtomType decode(XdrDataInputStream stream, int maxDepth) throws IOException {
    // maxDepth is intentionally not checked - enums are leaf types with no recursive decoding
    int value = stream.readInt();
    switch (value) {
      case 0:
        return CLAIM_ATOM_TYPE_V0;
      case 1:
        return CLAIM_ATOM_TYPE_ORDER_BOOK;
      case 2:
        return CLAIM_ATOM_TYPE_LIQUIDITY_POOL;
      default:
        throw new IllegalArgumentException("Unknown enum value: " + value);
    }
  }

  public static ClaimAtomType decode(XdrDataInputStream stream) throws IOException {
    return decode(stream, XdrDataInputStream.DEFAULT_MAX_DEPTH);
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    stream.writeInt(value);
  }

  public static ClaimAtomType fromXdrBase64(String xdr) throws IOException {
    byte[] bytes = Base64Factory.getInstance().decode(xdr);
    return fromXdrByteArray(bytes);
  }

  public static ClaimAtomType fromXdrByteArray(byte[] xdr) throws IOException {
    ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
    XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
    xdrDataInputStream.setMaxInputLen(xdr.length);
    return decode(xdrDataInputStream);
  }

  @Override
  public String toJson() {
    return XdrElement.gson.toJson(toJsonObject());
  }

  public static ClaimAtomType fromJson(String json) {
    return fromJsonObject(XdrElement.gson.fromJson(json, Object.class));
  }

  Object toJsonObject() {
    switch (this) {
      case CLAIM_ATOM_TYPE_V0:
        return "v0";
      case CLAIM_ATOM_TYPE_ORDER_BOOK:
        return "order_book";
      case CLAIM_ATOM_TYPE_LIQUIDITY_POOL:
        return "liquidity_pool";
      default:
        throw new IllegalArgumentException("Unknown enum value: " + this.value);
    }
  }

  static ClaimAtomType fromJsonObject(Object json) {
    String value = (String) json;
    switch (value) {
      case "v0":
        return CLAIM_ATOM_TYPE_V0;
      case "order_book":
        return CLAIM_ATOM_TYPE_ORDER_BOOK;
      case "liquidity_pool":
        return CLAIM_ATOM_TYPE_LIQUIDITY_POOL;
      default:
        throw new IllegalArgumentException("Unknown JSON value: " + value);
    }
  }
}
