// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;

import static org.stellar.sdk.xdr.Constants.*;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.Base64;
import java.util.Objects;

// === xdr source ============================================================

//  struct ConfigSettingContractLedgerCostV0
//  {
//      // Maximum number of ledger entry read operations per ledger
//      uint32 ledgerMaxReadLedgerEntries;
//      // Maximum number of bytes that can be read per ledger
//      uint32 ledgerMaxReadBytes;
//      // Maximum number of ledger entry write operations per ledger
//      uint32 ledgerMaxWriteLedgerEntries;
//      // Maximum number of bytes that can be written per ledger
//      uint32 ledgerMaxWriteBytes;
//
//      // Maximum number of ledger entry read operations per transaction
//      uint32 txMaxReadLedgerEntries;
//      // Maximum number of bytes that can be read per transaction
//      uint32 txMaxReadBytes;
//      // Maximum number of ledger entry write operations per transaction
//      uint32 txMaxWriteLedgerEntries;
//      // Maximum number of bytes that can be written per transaction
//      uint32 txMaxWriteBytes;
//
//      int64 feeReadLedgerEntry;  // Fee per ledger entry read
//      int64 feeWriteLedgerEntry; // Fee per ledger entry write
//
//      int64 feeRead1KB;  // Fee for reading 1KB
//      int64 feeWrite1KB; // Fee for writing 1KB
//
//      // Bucket list fees grow slowly up to that size
//      int64 bucketListSizeBytes;
//      // Fee rate in stroops when the bucket list is empty
//      int64 bucketListFeeRateLow;
//      // Fee rate in stroops when the bucket list reached bucketListSizeBytes
//      int64 bucketListFeeRateHigh;
//      // Rate multiplier for any additional data past the first bucketListSizeBytes
//      uint32 bucketListGrowthFactor;
//  };

//  ===========================================================================
public class ConfigSettingContractLedgerCostV0 implements XdrElement {
  public ConfigSettingContractLedgerCostV0() {}

  private Uint32 ledgerMaxReadLedgerEntries;

  public Uint32 getLedgerMaxReadLedgerEntries() {
    return this.ledgerMaxReadLedgerEntries;
  }

  public void setLedgerMaxReadLedgerEntries(Uint32 value) {
    this.ledgerMaxReadLedgerEntries = value;
  }

  private Uint32 ledgerMaxReadBytes;

  public Uint32 getLedgerMaxReadBytes() {
    return this.ledgerMaxReadBytes;
  }

  public void setLedgerMaxReadBytes(Uint32 value) {
    this.ledgerMaxReadBytes = value;
  }

  private Uint32 ledgerMaxWriteLedgerEntries;

  public Uint32 getLedgerMaxWriteLedgerEntries() {
    return this.ledgerMaxWriteLedgerEntries;
  }

  public void setLedgerMaxWriteLedgerEntries(Uint32 value) {
    this.ledgerMaxWriteLedgerEntries = value;
  }

  private Uint32 ledgerMaxWriteBytes;

  public Uint32 getLedgerMaxWriteBytes() {
    return this.ledgerMaxWriteBytes;
  }

  public void setLedgerMaxWriteBytes(Uint32 value) {
    this.ledgerMaxWriteBytes = value;
  }

  private Uint32 txMaxReadLedgerEntries;

  public Uint32 getTxMaxReadLedgerEntries() {
    return this.txMaxReadLedgerEntries;
  }

  public void setTxMaxReadLedgerEntries(Uint32 value) {
    this.txMaxReadLedgerEntries = value;
  }

  private Uint32 txMaxReadBytes;

  public Uint32 getTxMaxReadBytes() {
    return this.txMaxReadBytes;
  }

  public void setTxMaxReadBytes(Uint32 value) {
    this.txMaxReadBytes = value;
  }

  private Uint32 txMaxWriteLedgerEntries;

  public Uint32 getTxMaxWriteLedgerEntries() {
    return this.txMaxWriteLedgerEntries;
  }

  public void setTxMaxWriteLedgerEntries(Uint32 value) {
    this.txMaxWriteLedgerEntries = value;
  }

  private Uint32 txMaxWriteBytes;

  public Uint32 getTxMaxWriteBytes() {
    return this.txMaxWriteBytes;
  }

  public void setTxMaxWriteBytes(Uint32 value) {
    this.txMaxWriteBytes = value;
  }

  private Int64 feeReadLedgerEntry;

  public Int64 getFeeReadLedgerEntry() {
    return this.feeReadLedgerEntry;
  }

  public void setFeeReadLedgerEntry(Int64 value) {
    this.feeReadLedgerEntry = value;
  }

  private Int64 feeWriteLedgerEntry;

  public Int64 getFeeWriteLedgerEntry() {
    return this.feeWriteLedgerEntry;
  }

  public void setFeeWriteLedgerEntry(Int64 value) {
    this.feeWriteLedgerEntry = value;
  }

  private Int64 feeRead1KB;

  public Int64 getFeeRead1KB() {
    return this.feeRead1KB;
  }

  public void setFeeRead1KB(Int64 value) {
    this.feeRead1KB = value;
  }

  private Int64 feeWrite1KB;

  public Int64 getFeeWrite1KB() {
    return this.feeWrite1KB;
  }

  public void setFeeWrite1KB(Int64 value) {
    this.feeWrite1KB = value;
  }

  private Int64 bucketListSizeBytes;

  public Int64 getBucketListSizeBytes() {
    return this.bucketListSizeBytes;
  }

  public void setBucketListSizeBytes(Int64 value) {
    this.bucketListSizeBytes = value;
  }

  private Int64 bucketListFeeRateLow;

  public Int64 getBucketListFeeRateLow() {
    return this.bucketListFeeRateLow;
  }

  public void setBucketListFeeRateLow(Int64 value) {
    this.bucketListFeeRateLow = value;
  }

  private Int64 bucketListFeeRateHigh;

  public Int64 getBucketListFeeRateHigh() {
    return this.bucketListFeeRateHigh;
  }

  public void setBucketListFeeRateHigh(Int64 value) {
    this.bucketListFeeRateHigh = value;
  }

  private Uint32 bucketListGrowthFactor;

  public Uint32 getBucketListGrowthFactor() {
    return this.bucketListGrowthFactor;
  }

  public void setBucketListGrowthFactor(Uint32 value) {
    this.bucketListGrowthFactor = value;
  }

  public static void encode(
      XdrDataOutputStream stream,
      ConfigSettingContractLedgerCostV0 encodedConfigSettingContractLedgerCostV0)
      throws IOException {
    Uint32.encode(stream, encodedConfigSettingContractLedgerCostV0.ledgerMaxReadLedgerEntries);
    Uint32.encode(stream, encodedConfigSettingContractLedgerCostV0.ledgerMaxReadBytes);
    Uint32.encode(stream, encodedConfigSettingContractLedgerCostV0.ledgerMaxWriteLedgerEntries);
    Uint32.encode(stream, encodedConfigSettingContractLedgerCostV0.ledgerMaxWriteBytes);
    Uint32.encode(stream, encodedConfigSettingContractLedgerCostV0.txMaxReadLedgerEntries);
    Uint32.encode(stream, encodedConfigSettingContractLedgerCostV0.txMaxReadBytes);
    Uint32.encode(stream, encodedConfigSettingContractLedgerCostV0.txMaxWriteLedgerEntries);
    Uint32.encode(stream, encodedConfigSettingContractLedgerCostV0.txMaxWriteBytes);
    Int64.encode(stream, encodedConfigSettingContractLedgerCostV0.feeReadLedgerEntry);
    Int64.encode(stream, encodedConfigSettingContractLedgerCostV0.feeWriteLedgerEntry);
    Int64.encode(stream, encodedConfigSettingContractLedgerCostV0.feeRead1KB);
    Int64.encode(stream, encodedConfigSettingContractLedgerCostV0.feeWrite1KB);
    Int64.encode(stream, encodedConfigSettingContractLedgerCostV0.bucketListSizeBytes);
    Int64.encode(stream, encodedConfigSettingContractLedgerCostV0.bucketListFeeRateLow);
    Int64.encode(stream, encodedConfigSettingContractLedgerCostV0.bucketListFeeRateHigh);
    Uint32.encode(stream, encodedConfigSettingContractLedgerCostV0.bucketListGrowthFactor);
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }

  public static ConfigSettingContractLedgerCostV0 decode(XdrDataInputStream stream)
      throws IOException {
    ConfigSettingContractLedgerCostV0 decodedConfigSettingContractLedgerCostV0 =
        new ConfigSettingContractLedgerCostV0();
    decodedConfigSettingContractLedgerCostV0.ledgerMaxReadLedgerEntries = Uint32.decode(stream);
    decodedConfigSettingContractLedgerCostV0.ledgerMaxReadBytes = Uint32.decode(stream);
    decodedConfigSettingContractLedgerCostV0.ledgerMaxWriteLedgerEntries = Uint32.decode(stream);
    decodedConfigSettingContractLedgerCostV0.ledgerMaxWriteBytes = Uint32.decode(stream);
    decodedConfigSettingContractLedgerCostV0.txMaxReadLedgerEntries = Uint32.decode(stream);
    decodedConfigSettingContractLedgerCostV0.txMaxReadBytes = Uint32.decode(stream);
    decodedConfigSettingContractLedgerCostV0.txMaxWriteLedgerEntries = Uint32.decode(stream);
    decodedConfigSettingContractLedgerCostV0.txMaxWriteBytes = Uint32.decode(stream);
    decodedConfigSettingContractLedgerCostV0.feeReadLedgerEntry = Int64.decode(stream);
    decodedConfigSettingContractLedgerCostV0.feeWriteLedgerEntry = Int64.decode(stream);
    decodedConfigSettingContractLedgerCostV0.feeRead1KB = Int64.decode(stream);
    decodedConfigSettingContractLedgerCostV0.feeWrite1KB = Int64.decode(stream);
    decodedConfigSettingContractLedgerCostV0.bucketListSizeBytes = Int64.decode(stream);
    decodedConfigSettingContractLedgerCostV0.bucketListFeeRateLow = Int64.decode(stream);
    decodedConfigSettingContractLedgerCostV0.bucketListFeeRateHigh = Int64.decode(stream);
    decodedConfigSettingContractLedgerCostV0.bucketListGrowthFactor = Uint32.decode(stream);
    return decodedConfigSettingContractLedgerCostV0;
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        this.ledgerMaxReadLedgerEntries,
        this.ledgerMaxReadBytes,
        this.ledgerMaxWriteLedgerEntries,
        this.ledgerMaxWriteBytes,
        this.txMaxReadLedgerEntries,
        this.txMaxReadBytes,
        this.txMaxWriteLedgerEntries,
        this.txMaxWriteBytes,
        this.feeReadLedgerEntry,
        this.feeWriteLedgerEntry,
        this.feeRead1KB,
        this.feeWrite1KB,
        this.bucketListSizeBytes,
        this.bucketListFeeRateLow,
        this.bucketListFeeRateHigh,
        this.bucketListGrowthFactor);
  }

  @Override
  public boolean equals(Object object) {
    if (!(object instanceof ConfigSettingContractLedgerCostV0)) {
      return false;
    }

    ConfigSettingContractLedgerCostV0 other = (ConfigSettingContractLedgerCostV0) object;
    return Objects.equals(this.ledgerMaxReadLedgerEntries, other.ledgerMaxReadLedgerEntries)
        && Objects.equals(this.ledgerMaxReadBytes, other.ledgerMaxReadBytes)
        && Objects.equals(this.ledgerMaxWriteLedgerEntries, other.ledgerMaxWriteLedgerEntries)
        && Objects.equals(this.ledgerMaxWriteBytes, other.ledgerMaxWriteBytes)
        && Objects.equals(this.txMaxReadLedgerEntries, other.txMaxReadLedgerEntries)
        && Objects.equals(this.txMaxReadBytes, other.txMaxReadBytes)
        && Objects.equals(this.txMaxWriteLedgerEntries, other.txMaxWriteLedgerEntries)
        && Objects.equals(this.txMaxWriteBytes, other.txMaxWriteBytes)
        && Objects.equals(this.feeReadLedgerEntry, other.feeReadLedgerEntry)
        && Objects.equals(this.feeWriteLedgerEntry, other.feeWriteLedgerEntry)
        && Objects.equals(this.feeRead1KB, other.feeRead1KB)
        && Objects.equals(this.feeWrite1KB, other.feeWrite1KB)
        && Objects.equals(this.bucketListSizeBytes, other.bucketListSizeBytes)
        && Objects.equals(this.bucketListFeeRateLow, other.bucketListFeeRateLow)
        && Objects.equals(this.bucketListFeeRateHigh, other.bucketListFeeRateHigh)
        && Objects.equals(this.bucketListGrowthFactor, other.bucketListGrowthFactor);
  }

  @Override
  public String toXdrBase64() throws IOException {
    return Base64.getEncoder().encodeToString(toXdrByteArray());
  }

  @Override
  public byte[] toXdrByteArray() throws IOException {
    ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
    XdrDataOutputStream xdrDataOutputStream = new XdrDataOutputStream(byteArrayOutputStream);
    encode(xdrDataOutputStream);
    return byteArrayOutputStream.toByteArray();
  }

  public static ConfigSettingContractLedgerCostV0 fromXdrBase64(String xdr) throws IOException {
    byte[] bytes = Base64.getDecoder().decode(xdr);
    return fromXdrByteArray(bytes);
  }

  public static ConfigSettingContractLedgerCostV0 fromXdrByteArray(byte[] xdr) throws IOException {
    ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
    XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
    return decode(xdrDataInputStream);
  }

  public static final class Builder {
    private Uint32 ledgerMaxReadLedgerEntries;
    private Uint32 ledgerMaxReadBytes;
    private Uint32 ledgerMaxWriteLedgerEntries;
    private Uint32 ledgerMaxWriteBytes;
    private Uint32 txMaxReadLedgerEntries;
    private Uint32 txMaxReadBytes;
    private Uint32 txMaxWriteLedgerEntries;
    private Uint32 txMaxWriteBytes;
    private Int64 feeReadLedgerEntry;
    private Int64 feeWriteLedgerEntry;
    private Int64 feeRead1KB;
    private Int64 feeWrite1KB;
    private Int64 bucketListSizeBytes;
    private Int64 bucketListFeeRateLow;
    private Int64 bucketListFeeRateHigh;
    private Uint32 bucketListGrowthFactor;

    public Builder ledgerMaxReadLedgerEntries(Uint32 ledgerMaxReadLedgerEntries) {
      this.ledgerMaxReadLedgerEntries = ledgerMaxReadLedgerEntries;
      return this;
    }

    public Builder ledgerMaxReadBytes(Uint32 ledgerMaxReadBytes) {
      this.ledgerMaxReadBytes = ledgerMaxReadBytes;
      return this;
    }

    public Builder ledgerMaxWriteLedgerEntries(Uint32 ledgerMaxWriteLedgerEntries) {
      this.ledgerMaxWriteLedgerEntries = ledgerMaxWriteLedgerEntries;
      return this;
    }

    public Builder ledgerMaxWriteBytes(Uint32 ledgerMaxWriteBytes) {
      this.ledgerMaxWriteBytes = ledgerMaxWriteBytes;
      return this;
    }

    public Builder txMaxReadLedgerEntries(Uint32 txMaxReadLedgerEntries) {
      this.txMaxReadLedgerEntries = txMaxReadLedgerEntries;
      return this;
    }

    public Builder txMaxReadBytes(Uint32 txMaxReadBytes) {
      this.txMaxReadBytes = txMaxReadBytes;
      return this;
    }

    public Builder txMaxWriteLedgerEntries(Uint32 txMaxWriteLedgerEntries) {
      this.txMaxWriteLedgerEntries = txMaxWriteLedgerEntries;
      return this;
    }

    public Builder txMaxWriteBytes(Uint32 txMaxWriteBytes) {
      this.txMaxWriteBytes = txMaxWriteBytes;
      return this;
    }

    public Builder feeReadLedgerEntry(Int64 feeReadLedgerEntry) {
      this.feeReadLedgerEntry = feeReadLedgerEntry;
      return this;
    }

    public Builder feeWriteLedgerEntry(Int64 feeWriteLedgerEntry) {
      this.feeWriteLedgerEntry = feeWriteLedgerEntry;
      return this;
    }

    public Builder feeRead1KB(Int64 feeRead1KB) {
      this.feeRead1KB = feeRead1KB;
      return this;
    }

    public Builder feeWrite1KB(Int64 feeWrite1KB) {
      this.feeWrite1KB = feeWrite1KB;
      return this;
    }

    public Builder bucketListSizeBytes(Int64 bucketListSizeBytes) {
      this.bucketListSizeBytes = bucketListSizeBytes;
      return this;
    }

    public Builder bucketListFeeRateLow(Int64 bucketListFeeRateLow) {
      this.bucketListFeeRateLow = bucketListFeeRateLow;
      return this;
    }

    public Builder bucketListFeeRateHigh(Int64 bucketListFeeRateHigh) {
      this.bucketListFeeRateHigh = bucketListFeeRateHigh;
      return this;
    }

    public Builder bucketListGrowthFactor(Uint32 bucketListGrowthFactor) {
      this.bucketListGrowthFactor = bucketListGrowthFactor;
      return this;
    }

    public ConfigSettingContractLedgerCostV0 build() {
      ConfigSettingContractLedgerCostV0 val = new ConfigSettingContractLedgerCostV0();
      val.setLedgerMaxReadLedgerEntries(this.ledgerMaxReadLedgerEntries);
      val.setLedgerMaxReadBytes(this.ledgerMaxReadBytes);
      val.setLedgerMaxWriteLedgerEntries(this.ledgerMaxWriteLedgerEntries);
      val.setLedgerMaxWriteBytes(this.ledgerMaxWriteBytes);
      val.setTxMaxReadLedgerEntries(this.txMaxReadLedgerEntries);
      val.setTxMaxReadBytes(this.txMaxReadBytes);
      val.setTxMaxWriteLedgerEntries(this.txMaxWriteLedgerEntries);
      val.setTxMaxWriteBytes(this.txMaxWriteBytes);
      val.setFeeReadLedgerEntry(this.feeReadLedgerEntry);
      val.setFeeWriteLedgerEntry(this.feeWriteLedgerEntry);
      val.setFeeRead1KB(this.feeRead1KB);
      val.setFeeWrite1KB(this.feeWrite1KB);
      val.setBucketListSizeBytes(this.bucketListSizeBytes);
      val.setBucketListFeeRateLow(this.bucketListFeeRateLow);
      val.setBucketListFeeRateHigh(this.bucketListFeeRateHigh);
      val.setBucketListGrowthFactor(this.bucketListGrowthFactor);
      return val;
    }
  }
}
