// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.stellar.sdk.Base64Factory;

/**
 * ConfigSettingContractHistoricalDataV0's original definition in the XDR file is:
 *
 * <pre>
 * struct ConfigSettingContractHistoricalDataV0
 * {
 *     int64 feeHistorical1KB; // Fee for storing 1KB in archives
 * };
 * </pre>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
public class ConfigSettingContractHistoricalDataV0 implements XdrElement {
  private Int64 feeHistorical1KB;

  public void encode(XdrDataOutputStream stream) throws IOException {
    feeHistorical1KB.encode(stream);
  }

  public static ConfigSettingContractHistoricalDataV0 decode(
      XdrDataInputStream stream, int maxDepth) throws IOException {
    if (maxDepth <= 0) {
      throw new IOException("Maximum decoding depth reached");
    }
    maxDepth -= 1;
    ConfigSettingContractHistoricalDataV0 decodedConfigSettingContractHistoricalDataV0 =
        new ConfigSettingContractHistoricalDataV0();
    decodedConfigSettingContractHistoricalDataV0.feeHistorical1KB = Int64.decode(stream, maxDepth);
    return decodedConfigSettingContractHistoricalDataV0;
  }

  public static ConfigSettingContractHistoricalDataV0 decode(XdrDataInputStream stream)
      throws IOException {
    return decode(stream, XdrDataInputStream.DEFAULT_MAX_DEPTH);
  }

  public static ConfigSettingContractHistoricalDataV0 fromXdrBase64(String xdr) throws IOException {
    byte[] bytes = Base64Factory.getInstance().decode(xdr);
    return fromXdrByteArray(bytes);
  }

  public static ConfigSettingContractHistoricalDataV0 fromXdrByteArray(byte[] xdr)
      throws IOException {
    ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
    XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
    xdrDataInputStream.setMaxInputLen(xdr.length);
    return decode(xdrDataInputStream);
  }
}
