// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.LinkedHashMap;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.stellar.sdk.Base64Factory;

/**
 * ConfigSettingContractEventsV0's original definition in the XDR file is:
 *
 * <pre>
 * struct ConfigSettingContractEventsV0
 * {
 *     // Maximum size of events that a contract call can emit.
 *     uint32 txMaxContractEventsSizeBytes;
 *     // Fee for generating 1KB of contract events.
 *     int64 feeContractEvents1KB;
 * };
 * </pre>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
public class ConfigSettingContractEventsV0 implements XdrElement {
  private Uint32 txMaxContractEventsSizeBytes;
  private Int64 feeContractEvents1KB;

  public void encode(XdrDataOutputStream stream) throws IOException {
    txMaxContractEventsSizeBytes.encode(stream);
    feeContractEvents1KB.encode(stream);
  }

  public static ConfigSettingContractEventsV0 decode(XdrDataInputStream stream, int maxDepth)
      throws IOException {
    if (maxDepth <= 0) {
      throw new IOException("Maximum decoding depth reached");
    }
    maxDepth -= 1;
    ConfigSettingContractEventsV0 decodedConfigSettingContractEventsV0 =
        new ConfigSettingContractEventsV0();
    decodedConfigSettingContractEventsV0.txMaxContractEventsSizeBytes =
        Uint32.decode(stream, maxDepth);
    decodedConfigSettingContractEventsV0.feeContractEvents1KB = Int64.decode(stream, maxDepth);
    return decodedConfigSettingContractEventsV0;
  }

  public static ConfigSettingContractEventsV0 decode(XdrDataInputStream stream) throws IOException {
    return decode(stream, XdrDataInputStream.DEFAULT_MAX_DEPTH);
  }

  public static ConfigSettingContractEventsV0 fromXdrBase64(String xdr) throws IOException {
    byte[] bytes = Base64Factory.getInstance().decode(xdr);
    return fromXdrByteArray(bytes);
  }

  public static ConfigSettingContractEventsV0 fromXdrByteArray(byte[] xdr) throws IOException {
    ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
    XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
    xdrDataInputStream.setMaxInputLen(xdr.length);
    return decode(xdrDataInputStream);
  }

  @Override
  public String toJson() {
    return XdrElement.gson.toJson(toJsonObject());
  }

  public static ConfigSettingContractEventsV0 fromJson(String json) {
    return fromJsonObject(XdrElement.gson.fromJson(json, Object.class));
  }

  Object toJsonObject() {
    LinkedHashMap<String, Object> jsonMap = new LinkedHashMap<>();
    jsonMap.put("tx_max_contract_events_size_bytes", txMaxContractEventsSizeBytes.toJsonObject());
    jsonMap.put("fee_contract_events1_kb", feeContractEvents1KB.toJsonObject());
    return jsonMap;
  }

  @SuppressWarnings("unchecked")
  static ConfigSettingContractEventsV0 fromJsonObject(Object json) {
    java.util.Map<String, Object> jsonMap = (java.util.Map<String, Object>) json;
    ConfigSettingContractEventsV0 instance = new ConfigSettingContractEventsV0();
    instance.txMaxContractEventsSizeBytes =
        Uint32.fromJsonObject(jsonMap.get("tx_max_contract_events_size_bytes"));
    instance.feeContractEvents1KB = Int64.fromJsonObject(jsonMap.get("fee_contract_events1_kb"));
    return instance;
  }
}
