// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;

import static org.stellar.sdk.xdr.Constants.*;

import java.io.IOException;

// === xdr source ============================================================

//  enum ContractEventType
//  {
//      SYSTEM = 0,
//      CONTRACT = 1,
//      DIAGNOSTIC = 2
//  };

//  ===========================================================================
public enum ContractEventType implements XdrElement {
  SYSTEM(0),
  CONTRACT(1),
  DIAGNOSTIC(2),
  ;
  private int mValue;

  ContractEventType(int value) {
    mValue = value;
  }

  public int getValue() {
    return mValue;
  }

  public static ContractEventType decode(XdrDataInputStream stream) throws IOException {
    int value = stream.readInt();
    switch (value) {
      case 0:
        return SYSTEM;
      case 1:
        return CONTRACT;
      case 2:
        return DIAGNOSTIC;
      default:
        throw new RuntimeException("Unknown enum value: " + value);
    }
  }

  public static void encode(XdrDataOutputStream stream, ContractEventType value)
      throws IOException {
    stream.writeInt(value.getValue());
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }
}
