// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.stellar.sdk.Base64Factory;

/**
 * DontHave's original definition in the XDR file is:
 *
 * <pre>
 * struct DontHave
 * {
 *     MessageType type;
 *     uint256 reqHash;
 * };
 * </pre>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
public class DontHave implements XdrElement {
  private MessageType type;
  private Uint256 reqHash;

  public void encode(XdrDataOutputStream stream) throws IOException {
    type.encode(stream);
    reqHash.encode(stream);
  }

  public static DontHave decode(XdrDataInputStream stream, int maxDepth) throws IOException {
    if (maxDepth <= 0) {
      throw new IOException("Maximum decoding depth reached");
    }
    maxDepth -= 1;
    DontHave decodedDontHave = new DontHave();
    decodedDontHave.type = MessageType.decode(stream, maxDepth);
    decodedDontHave.reqHash = Uint256.decode(stream, maxDepth);
    return decodedDontHave;
  }

  public static DontHave decode(XdrDataInputStream stream) throws IOException {
    return decode(stream, XdrDataInputStream.DEFAULT_MAX_DEPTH);
  }

  public static DontHave fromXdrBase64(String xdr) throws IOException {
    byte[] bytes = Base64Factory.getInstance().decode(xdr);
    return fromXdrByteArray(bytes);
  }

  public static DontHave fromXdrByteArray(byte[] xdr) throws IOException {
    ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
    XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
    xdrDataInputStream.setMaxInputLen(xdr.length);
    return decode(xdrDataInputStream);
  }
}
