// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;


import com.google.common.base.Objects;

import java.io.IOException;

// === xdr source ============================================================

//  typedef int64 Duration;

//  ===========================================================================
public class Duration implements XdrElement {
  private Int64 Duration;

  public Duration() {}

  public Duration(Int64 Duration) {
    this.Duration = Duration;
  }

  public Int64 getDuration() {
    return this.Duration;
  }

  public void setDuration(Int64 value) {
    this.Duration = value;
  }

  public static void encode(XdrDataOutputStream stream, Duration  encodedDuration) throws IOException {
    Int64.encode(stream, encodedDuration.Duration);
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }
  public static Duration decode(XdrDataInputStream stream) throws IOException {
    Duration decodedDuration = new Duration();
    decodedDuration.Duration = Int64.decode(stream);
    return decodedDuration;
  }

  @Override
  public int hashCode() {
    return Objects.hashCode(this.Duration);
  }

  @Override
  public boolean equals(Object object) {
    if (!(object instanceof Duration)) {
      return false;
    }

    Duration other = (Duration) object;
    return Objects.equal(this.Duration, other.Duration);
  }
}
