// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import org.stellar.sdk.Base64Factory;

/**
 * ExtendFootprintTTLResultCode's original definition in the XDR file is:
 *
 * <pre>
 * enum ExtendFootprintTTLResultCode
 * {
 *     // codes considered as "success" for the operation
 *     EXTEND_FOOTPRINT_TTL_SUCCESS = 0,
 *
 *     // codes considered as "failure" for the operation
 *     EXTEND_FOOTPRINT_TTL_MALFORMED = -1,
 *     EXTEND_FOOTPRINT_TTL_RESOURCE_LIMIT_EXCEEDED = -2,
 *     EXTEND_FOOTPRINT_TTL_INSUFFICIENT_REFUNDABLE_FEE = -3
 * };
 * </pre>
 */
public enum ExtendFootprintTTLResultCode implements XdrElement {
  EXTEND_FOOTPRINT_TTL_SUCCESS(0),
  EXTEND_FOOTPRINT_TTL_MALFORMED(-1),
  EXTEND_FOOTPRINT_TTL_RESOURCE_LIMIT_EXCEEDED(-2),
  EXTEND_FOOTPRINT_TTL_INSUFFICIENT_REFUNDABLE_FEE(-3);

  private final int value;

  ExtendFootprintTTLResultCode(int value) {
    this.value = value;
  }

  public int getValue() {
    return value;
  }

  public static ExtendFootprintTTLResultCode decode(XdrDataInputStream stream) throws IOException {
    int value = stream.readInt();
    switch (value) {
      case 0:
        return EXTEND_FOOTPRINT_TTL_SUCCESS;
      case -1:
        return EXTEND_FOOTPRINT_TTL_MALFORMED;
      case -2:
        return EXTEND_FOOTPRINT_TTL_RESOURCE_LIMIT_EXCEEDED;
      case -3:
        return EXTEND_FOOTPRINT_TTL_INSUFFICIENT_REFUNDABLE_FEE;
      default:
        throw new IllegalArgumentException("Unknown enum value: " + value);
    }
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    stream.writeInt(value);
  }

  public static ExtendFootprintTTLResultCode fromXdrBase64(String xdr) throws IOException {
    byte[] bytes = Base64Factory.getInstance().decode(xdr);
    return fromXdrByteArray(bytes);
  }

  public static ExtendFootprintTTLResultCode fromXdrByteArray(byte[] xdr) throws IOException {
    ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
    XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
    return decode(xdrDataInputStream);
  }
}
