// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.LinkedHashMap;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.stellar.sdk.Base64Factory;

/**
 * FeeBumpTransaction's original definition in the XDR file is:
 *
 * <pre>
 * struct FeeBumpTransaction
 * {
 *     MuxedAccount feeSource;
 *     int64 fee;
 *     union switch (EnvelopeType type)
 *     {
 *     case ENVELOPE_TYPE_TX:
 *         TransactionV1Envelope v1;
 *     }
 *     innerTx;
 *     union switch (int v)
 *     {
 *     case 0:
 *         void;
 *     }
 *     ext;
 * };
 * </pre>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
public class FeeBumpTransaction implements XdrElement {
  private MuxedAccount feeSource;
  private Int64 fee;
  private FeeBumpTransactionInnerTx innerTx;
  private FeeBumpTransactionExt ext;

  public void encode(XdrDataOutputStream stream) throws IOException {
    feeSource.encode(stream);
    fee.encode(stream);
    innerTx.encode(stream);
    ext.encode(stream);
  }

  public static FeeBumpTransaction decode(XdrDataInputStream stream, int maxDepth)
      throws IOException {
    if (maxDepth <= 0) {
      throw new IOException("Maximum decoding depth reached");
    }
    maxDepth -= 1;
    FeeBumpTransaction decodedFeeBumpTransaction = new FeeBumpTransaction();
    decodedFeeBumpTransaction.feeSource = MuxedAccount.decode(stream, maxDepth);
    decodedFeeBumpTransaction.fee = Int64.decode(stream, maxDepth);
    decodedFeeBumpTransaction.innerTx = FeeBumpTransactionInnerTx.decode(stream, maxDepth);
    decodedFeeBumpTransaction.ext = FeeBumpTransactionExt.decode(stream, maxDepth);
    return decodedFeeBumpTransaction;
  }

  public static FeeBumpTransaction decode(XdrDataInputStream stream) throws IOException {
    return decode(stream, XdrDataInputStream.DEFAULT_MAX_DEPTH);
  }

  public static FeeBumpTransaction fromXdrBase64(String xdr) throws IOException {
    byte[] bytes = Base64Factory.getInstance().decode(xdr);
    return fromXdrByteArray(bytes);
  }

  public static FeeBumpTransaction fromXdrByteArray(byte[] xdr) throws IOException {
    ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
    XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
    xdrDataInputStream.setMaxInputLen(xdr.length);
    return decode(xdrDataInputStream);
  }

  @Override
  public String toJson() {
    return XdrElement.gson.toJson(toJsonObject());
  }

  public static FeeBumpTransaction fromJson(String json) {
    return fromJsonObject(XdrElement.gson.fromJson(json, Object.class));
  }

  Object toJsonObject() {
    LinkedHashMap<String, Object> jsonMap = new LinkedHashMap<>();
    jsonMap.put("fee_source", feeSource.toJsonObject());
    jsonMap.put("fee", fee.toJsonObject());
    jsonMap.put("inner_tx", innerTx.toJsonObject());
    jsonMap.put("ext", ext.toJsonObject());
    return jsonMap;
  }

  @SuppressWarnings("unchecked")
  static FeeBumpTransaction fromJsonObject(Object json) {
    java.util.Map<String, Object> jsonMap = (java.util.Map<String, Object>) json;
    FeeBumpTransaction instance = new FeeBumpTransaction();
    instance.feeSource = MuxedAccount.fromJsonObject(jsonMap.get("fee_source"));
    instance.fee = Int64.fromJsonObject(jsonMap.get("fee"));
    instance.innerTx = FeeBumpTransactionInnerTx.fromJsonObject(jsonMap.get("inner_tx"));
    instance.ext = FeeBumpTransactionExt.fromJsonObject(jsonMap.get("ext"));
    return instance;
  }

  /**
   * FeeBumpTransactionInnerTx's original definition in the XDR file is:
   *
   * <pre>
   * union switch (EnvelopeType type)
   *     {
   *     case ENVELOPE_TYPE_TX:
   *         TransactionV1Envelope v1;
   *     }
   * </pre>
   */
  @Data
  @NoArgsConstructor
  @AllArgsConstructor
  @Builder(toBuilder = true)
  public static class FeeBumpTransactionInnerTx implements XdrElement {
    private EnvelopeType discriminant;
    private TransactionV1Envelope v1;

    public void encode(XdrDataOutputStream stream) throws IOException {
      stream.writeInt(discriminant.getValue());
      switch (discriminant) {
        case ENVELOPE_TYPE_TX:
          v1.encode(stream);
          break;
      }
    }

    public static FeeBumpTransactionInnerTx decode(XdrDataInputStream stream, int maxDepth)
        throws IOException {
      if (maxDepth <= 0) {
        throw new IOException("Maximum decoding depth reached");
      }
      maxDepth -= 1;
      FeeBumpTransactionInnerTx decodedFeeBumpTransactionInnerTx = new FeeBumpTransactionInnerTx();
      EnvelopeType discriminant = EnvelopeType.decode(stream, maxDepth);
      decodedFeeBumpTransactionInnerTx.setDiscriminant(discriminant);
      switch (decodedFeeBumpTransactionInnerTx.getDiscriminant()) {
        case ENVELOPE_TYPE_TX:
          decodedFeeBumpTransactionInnerTx.v1 = TransactionV1Envelope.decode(stream, maxDepth);
          break;
        default:
          throw new IOException("Unknown discriminant value: " + discriminant);
      }
      return decodedFeeBumpTransactionInnerTx;
    }

    public static FeeBumpTransactionInnerTx decode(XdrDataInputStream stream) throws IOException {
      return decode(stream, XdrDataInputStream.DEFAULT_MAX_DEPTH);
    }

    public static FeeBumpTransactionInnerTx fromXdrBase64(String xdr) throws IOException {
      byte[] bytes = Base64Factory.getInstance().decode(xdr);
      return fromXdrByteArray(bytes);
    }

    public static FeeBumpTransactionInnerTx fromXdrByteArray(byte[] xdr) throws IOException {
      ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
      XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
      xdrDataInputStream.setMaxInputLen(xdr.length);
      return decode(xdrDataInputStream);
    }

    @Override
    public String toJson() {
      return XdrElement.gson.toJson(toJsonObject());
    }

    public static FeeBumpTransactionInnerTx fromJson(String json) {
      return fromJsonObject(XdrElement.gson.fromJson(json, Object.class));
    }

    Object toJsonObject() {
      if (discriminant == EnvelopeType.ENVELOPE_TYPE_TX) {
        LinkedHashMap<String, Object> jsonMap = new LinkedHashMap<>();
        jsonMap.put("tx", v1.toJsonObject());
        return jsonMap;
      }
      throw new IllegalArgumentException("Unknown discriminant: " + discriminant);
    }

    @SuppressWarnings("unchecked")
    static FeeBumpTransactionInnerTx fromJsonObject(Object json) {
      java.util.Map<String, Object> jsonMap = (java.util.Map<String, Object>) json;
      if (jsonMap.containsKey("$schema")) {
        jsonMap = new LinkedHashMap<>(jsonMap);
        jsonMap.remove("$schema");
      }
      if (jsonMap.size() != 1) {
        throw new IllegalArgumentException(
            "Expected a single-key object for FeeBumpTransactionInnerTx, got: " + json);
      }
      String key = jsonMap.keySet().iterator().next();
      EnvelopeType discriminant = EnvelopeType.fromJsonObject(key);
      if (key.equals("tx")) {
        FeeBumpTransactionInnerTx instance = new FeeBumpTransactionInnerTx();
        instance.discriminant = discriminant;
        instance.v1 = TransactionV1Envelope.fromJsonObject(jsonMap.get("tx"));
        return instance;
      }
      throw new IllegalArgumentException("Unknown key '" + key + "' for FeeBumpTransactionInnerTx");
    }
  }

  /**
   * FeeBumpTransactionExt's original definition in the XDR file is:
   *
   * <pre>
   * union switch (int v)
   *     {
   *     case 0:
   *         void;
   *     }
   * </pre>
   */
  @Data
  @NoArgsConstructor
  @AllArgsConstructor
  @Builder(toBuilder = true)
  public static class FeeBumpTransactionExt implements XdrElement {
    private Integer discriminant;

    public void encode(XdrDataOutputStream stream) throws IOException {
      stream.writeInt(discriminant);
      switch (discriminant) {
        case 0:
          break;
      }
    }

    public static FeeBumpTransactionExt decode(XdrDataInputStream stream, int maxDepth)
        throws IOException {
      if (maxDepth <= 0) {
        throw new IOException("Maximum decoding depth reached");
      }
      maxDepth -= 1;
      FeeBumpTransactionExt decodedFeeBumpTransactionExt = new FeeBumpTransactionExt();
      Integer discriminant = stream.readInt();
      decodedFeeBumpTransactionExt.setDiscriminant(discriminant);
      switch (decodedFeeBumpTransactionExt.getDiscriminant()) {
        case 0:
          break;
        default:
          throw new IOException("Unknown discriminant value: " + discriminant);
      }
      return decodedFeeBumpTransactionExt;
    }

    public static FeeBumpTransactionExt decode(XdrDataInputStream stream) throws IOException {
      return decode(stream, XdrDataInputStream.DEFAULT_MAX_DEPTH);
    }

    public static FeeBumpTransactionExt fromXdrBase64(String xdr) throws IOException {
      byte[] bytes = Base64Factory.getInstance().decode(xdr);
      return fromXdrByteArray(bytes);
    }

    public static FeeBumpTransactionExt fromXdrByteArray(byte[] xdr) throws IOException {
      ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
      XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
      xdrDataInputStream.setMaxInputLen(xdr.length);
      return decode(xdrDataInputStream);
    }

    @Override
    public String toJson() {
      return XdrElement.gson.toJson(toJsonObject());
    }

    public static FeeBumpTransactionExt fromJson(String json) {
      return fromJsonObject(XdrElement.gson.fromJson(json, Object.class));
    }

    Object toJsonObject() {
      if (discriminant == 0) {
        return "v0";
      }
      throw new IllegalArgumentException("Unknown discriminant: " + discriminant);
    }

    @SuppressWarnings("unchecked")
    static FeeBumpTransactionExt fromJsonObject(Object json) {
      if (json instanceof String) {
        String strVal = (String) json;
        if (!(strVal.equals("v0"))) {
          throw new IllegalArgumentException(
              "Unexpected string '" + strVal + "' for FeeBumpTransactionExt");
        }
        FeeBumpTransactionExt instance = new FeeBumpTransactionExt();
        instance.discriminant = Integer.parseInt(strVal.substring(1));
        return instance;
      }
      throw new IllegalArgumentException(
          "Expected a string for FeeBumpTransactionExt, got: " + json);
    }
  }
}
