// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.LinkedHashMap;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.stellar.sdk.Base64Factory;

/**
 * InnerTransactionResult's original definition in the XDR file is:
 *
 * <pre>
 * struct InnerTransactionResult
 * {
 *     // Always 0. Here for binary compatibility.
 *     int64 feeCharged;
 *
 *     union switch (TransactionResultCode code)
 *     {
 *     // txFEE_BUMP_INNER_SUCCESS is not included
 *     case txSUCCESS:
 *     case txFAILED:
 *         OperationResult results&lt;&gt;;
 *     case txTOO_EARLY:
 *     case txTOO_LATE:
 *     case txMISSING_OPERATION:
 *     case txBAD_SEQ:
 *     case txBAD_AUTH:
 *     case txINSUFFICIENT_BALANCE:
 *     case txNO_ACCOUNT:
 *     case txINSUFFICIENT_FEE:
 *     case txBAD_AUTH_EXTRA:
 *     case txINTERNAL_ERROR:
 *     case txNOT_SUPPORTED:
 *     // txFEE_BUMP_INNER_FAILED is not included
 *     case txBAD_SPONSORSHIP:
 *     case txBAD_MIN_SEQ_AGE_OR_GAP:
 *     case txMALFORMED:
 *     case txSOROBAN_INVALID:
 *         void;
 *     }
 *     result;
 *
 *     // reserved for future use
 *     union switch (int v)
 *     {
 *     case 0:
 *         void;
 *     }
 *     ext;
 * };
 * </pre>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
public class InnerTransactionResult implements XdrElement {
  private Int64 feeCharged;
  private InnerTransactionResultResult result;
  private InnerTransactionResultExt ext;

  public void encode(XdrDataOutputStream stream) throws IOException {
    feeCharged.encode(stream);
    result.encode(stream);
    ext.encode(stream);
  }

  public static InnerTransactionResult decode(XdrDataInputStream stream, int maxDepth)
      throws IOException {
    if (maxDepth <= 0) {
      throw new IOException("Maximum decoding depth reached");
    }
    maxDepth -= 1;
    InnerTransactionResult decodedInnerTransactionResult = new InnerTransactionResult();
    decodedInnerTransactionResult.feeCharged = Int64.decode(stream, maxDepth);
    decodedInnerTransactionResult.result = InnerTransactionResultResult.decode(stream, maxDepth);
    decodedInnerTransactionResult.ext = InnerTransactionResultExt.decode(stream, maxDepth);
    return decodedInnerTransactionResult;
  }

  public static InnerTransactionResult decode(XdrDataInputStream stream) throws IOException {
    return decode(stream, XdrDataInputStream.DEFAULT_MAX_DEPTH);
  }

  public static InnerTransactionResult fromXdrBase64(String xdr) throws IOException {
    byte[] bytes = Base64Factory.getInstance().decode(xdr);
    return fromXdrByteArray(bytes);
  }

  public static InnerTransactionResult fromXdrByteArray(byte[] xdr) throws IOException {
    ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
    XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
    xdrDataInputStream.setMaxInputLen(xdr.length);
    return decode(xdrDataInputStream);
  }

  @Override
  public String toJson() {
    return XdrElement.gson.toJson(toJsonObject());
  }

  public static InnerTransactionResult fromJson(String json) {
    return fromJsonObject(XdrElement.gson.fromJson(json, Object.class));
  }

  Object toJsonObject() {
    LinkedHashMap<String, Object> jsonMap = new LinkedHashMap<>();
    jsonMap.put("fee_charged", feeCharged.toJsonObject());
    jsonMap.put("result", result.toJsonObject());
    jsonMap.put("ext", ext.toJsonObject());
    return jsonMap;
  }

  @SuppressWarnings("unchecked")
  static InnerTransactionResult fromJsonObject(Object json) {
    java.util.Map<String, Object> jsonMap = (java.util.Map<String, Object>) json;
    InnerTransactionResult instance = new InnerTransactionResult();
    instance.feeCharged = Int64.fromJsonObject(jsonMap.get("fee_charged"));
    instance.result = InnerTransactionResultResult.fromJsonObject(jsonMap.get("result"));
    instance.ext = InnerTransactionResultExt.fromJsonObject(jsonMap.get("ext"));
    return instance;
  }

  /**
   * InnerTransactionResultResult's original definition in the XDR file is:
   *
   * <pre>
   * union switch (TransactionResultCode code)
   *     {
   *     // txFEE_BUMP_INNER_SUCCESS is not included
   *     case txSUCCESS:
   *     case txFAILED:
   *         OperationResult results&lt;&gt;;
   *     case txTOO_EARLY:
   *     case txTOO_LATE:
   *     case txMISSING_OPERATION:
   *     case txBAD_SEQ:
   *     case txBAD_AUTH:
   *     case txINSUFFICIENT_BALANCE:
   *     case txNO_ACCOUNT:
   *     case txINSUFFICIENT_FEE:
   *     case txBAD_AUTH_EXTRA:
   *     case txINTERNAL_ERROR:
   *     case txNOT_SUPPORTED:
   *     // txFEE_BUMP_INNER_FAILED is not included
   *     case txBAD_SPONSORSHIP:
   *     case txBAD_MIN_SEQ_AGE_OR_GAP:
   *     case txMALFORMED:
   *     case txSOROBAN_INVALID:
   *         void;
   *     }
   * </pre>
   */
  @Data
  @NoArgsConstructor
  @AllArgsConstructor
  @Builder(toBuilder = true)
  public static class InnerTransactionResultResult implements XdrElement {
    private TransactionResultCode discriminant;
    private OperationResult[] results;

    public void encode(XdrDataOutputStream stream) throws IOException {
      stream.writeInt(discriminant.getValue());
      switch (discriminant) {
        case txSUCCESS:
        case txFAILED:
          int resultsSize = getResults().length;
          stream.writeInt(resultsSize);
          for (int i = 0; i < resultsSize; i++) {
            results[i].encode(stream);
          }
          break;
        case txTOO_EARLY:
        case txTOO_LATE:
        case txMISSING_OPERATION:
        case txBAD_SEQ:
        case txBAD_AUTH:
        case txINSUFFICIENT_BALANCE:
        case txNO_ACCOUNT:
        case txINSUFFICIENT_FEE:
        case txBAD_AUTH_EXTRA:
        case txINTERNAL_ERROR:
        case txNOT_SUPPORTED:
        case txBAD_SPONSORSHIP:
        case txBAD_MIN_SEQ_AGE_OR_GAP:
        case txMALFORMED:
        case txSOROBAN_INVALID:
          break;
      }
    }

    public static InnerTransactionResultResult decode(XdrDataInputStream stream, int maxDepth)
        throws IOException {
      if (maxDepth <= 0) {
        throw new IOException("Maximum decoding depth reached");
      }
      maxDepth -= 1;
      InnerTransactionResultResult decodedInnerTransactionResultResult =
          new InnerTransactionResultResult();
      TransactionResultCode discriminant = TransactionResultCode.decode(stream, maxDepth);
      decodedInnerTransactionResultResult.setDiscriminant(discriminant);
      switch (decodedInnerTransactionResultResult.getDiscriminant()) {
        case txSUCCESS:
        case txFAILED:
          int resultsSize = stream.readInt();
          if (resultsSize < 0) {
            throw new IOException("results size " + resultsSize + " is negative");
          }
          int resultsRemainingInputLen = stream.getRemainingInputLen();
          if (resultsRemainingInputLen >= 0 && resultsRemainingInputLen < resultsSize) {
            throw new IOException(
                "results size "
                    + resultsSize
                    + " exceeds remaining input length "
                    + resultsRemainingInputLen);
          }
          decodedInnerTransactionResultResult.results = new OperationResult[resultsSize];
          for (int i = 0; i < resultsSize; i++) {
            decodedInnerTransactionResultResult.results[i] =
                OperationResult.decode(stream, maxDepth);
          }
          break;
        case txTOO_EARLY:
        case txTOO_LATE:
        case txMISSING_OPERATION:
        case txBAD_SEQ:
        case txBAD_AUTH:
        case txINSUFFICIENT_BALANCE:
        case txNO_ACCOUNT:
        case txINSUFFICIENT_FEE:
        case txBAD_AUTH_EXTRA:
        case txINTERNAL_ERROR:
        case txNOT_SUPPORTED:
        case txBAD_SPONSORSHIP:
        case txBAD_MIN_SEQ_AGE_OR_GAP:
        case txMALFORMED:
        case txSOROBAN_INVALID:
          break;
        default:
          throw new IOException("Unknown discriminant value: " + discriminant);
      }
      return decodedInnerTransactionResultResult;
    }

    public static InnerTransactionResultResult decode(XdrDataInputStream stream)
        throws IOException {
      return decode(stream, XdrDataInputStream.DEFAULT_MAX_DEPTH);
    }

    public static InnerTransactionResultResult fromXdrBase64(String xdr) throws IOException {
      byte[] bytes = Base64Factory.getInstance().decode(xdr);
      return fromXdrByteArray(bytes);
    }

    public static InnerTransactionResultResult fromXdrByteArray(byte[] xdr) throws IOException {
      ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
      XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
      xdrDataInputStream.setMaxInputLen(xdr.length);
      return decode(xdrDataInputStream);
    }

    @Override
    public String toJson() {
      return XdrElement.gson.toJson(toJsonObject());
    }

    public static InnerTransactionResultResult fromJson(String json) {
      return fromJsonObject(XdrElement.gson.fromJson(json, Object.class));
    }

    Object toJsonObject() {
      if (discriminant == TransactionResultCode.txSUCCESS) {
        LinkedHashMap<String, Object> jsonMap = new LinkedHashMap<>();
        jsonMap.put(
            "txsuccess", XdrElement.arrayToJsonArray(results, i -> results[i].toJsonObject()));
        return jsonMap;
      }
      if (discriminant == TransactionResultCode.txFAILED) {
        LinkedHashMap<String, Object> jsonMap = new LinkedHashMap<>();
        jsonMap.put(
            "txfailed", XdrElement.arrayToJsonArray(results, i -> results[i].toJsonObject()));
        return jsonMap;
      }
      if (discriminant == TransactionResultCode.txTOO_EARLY) {
        return "txtoo_early";
      }
      if (discriminant == TransactionResultCode.txTOO_LATE) {
        return "txtoo_late";
      }
      if (discriminant == TransactionResultCode.txMISSING_OPERATION) {
        return "txmissing_operation";
      }
      if (discriminant == TransactionResultCode.txBAD_SEQ) {
        return "txbad_seq";
      }
      if (discriminant == TransactionResultCode.txBAD_AUTH) {
        return "txbad_auth";
      }
      if (discriminant == TransactionResultCode.txINSUFFICIENT_BALANCE) {
        return "txinsufficient_balance";
      }
      if (discriminant == TransactionResultCode.txNO_ACCOUNT) {
        return "txno_account";
      }
      if (discriminant == TransactionResultCode.txINSUFFICIENT_FEE) {
        return "txinsufficient_fee";
      }
      if (discriminant == TransactionResultCode.txBAD_AUTH_EXTRA) {
        return "txbad_auth_extra";
      }
      if (discriminant == TransactionResultCode.txINTERNAL_ERROR) {
        return "txinternal_error";
      }
      if (discriminant == TransactionResultCode.txNOT_SUPPORTED) {
        return "txnot_supported";
      }
      if (discriminant == TransactionResultCode.txBAD_SPONSORSHIP) {
        return "txbad_sponsorship";
      }
      if (discriminant == TransactionResultCode.txBAD_MIN_SEQ_AGE_OR_GAP) {
        return "txbad_min_seq_age_or_gap";
      }
      if (discriminant == TransactionResultCode.txMALFORMED) {
        return "txmalformed";
      }
      if (discriminant == TransactionResultCode.txSOROBAN_INVALID) {
        return "txsoroban_invalid";
      }
      throw new IllegalArgumentException("Unknown discriminant: " + discriminant);
    }

    @SuppressWarnings("unchecked")
    static InnerTransactionResultResult fromJsonObject(Object json) {
      if (json instanceof String) {
        String strVal = (String) json;
        if (!(strVal.equals("txtoo_early")
            || strVal.equals("txtoo_late")
            || strVal.equals("txmissing_operation")
            || strVal.equals("txbad_seq")
            || strVal.equals("txbad_auth")
            || strVal.equals("txinsufficient_balance")
            || strVal.equals("txno_account")
            || strVal.equals("txinsufficient_fee")
            || strVal.equals("txbad_auth_extra")
            || strVal.equals("txinternal_error")
            || strVal.equals("txnot_supported")
            || strVal.equals("txbad_sponsorship")
            || strVal.equals("txbad_min_seq_age_or_gap")
            || strVal.equals("txmalformed")
            || strVal.equals("txsoroban_invalid"))) {
          throw new IllegalArgumentException(
              "Unexpected string '" + strVal + "' for InnerTransactionResultResult");
        }
        InnerTransactionResultResult instance = new InnerTransactionResultResult();
        instance.discriminant = TransactionResultCode.fromJsonObject(strVal);
        return instance;
      }
      java.util.Map<String, Object> jsonMap = (java.util.Map<String, Object>) json;
      if (jsonMap.containsKey("$schema")) {
        jsonMap = new LinkedHashMap<>(jsonMap);
        jsonMap.remove("$schema");
      }
      if (jsonMap.size() != 1) {
        throw new IllegalArgumentException(
            "Expected a single-key object for InnerTransactionResultResult, got: " + json);
      }
      String key = jsonMap.keySet().iterator().next();
      TransactionResultCode discriminant = TransactionResultCode.fromJsonObject(key);
      if (key.equals("txsuccess")) {
        InnerTransactionResultResult instance = new InnerTransactionResultResult();
        instance.discriminant = discriminant;
        instance.results =
            XdrElement.jsonArrayToArray(
                (List<Object>) jsonMap.get("txsuccess"),
                OperationResult.class,
                item -> OperationResult.fromJsonObject(item));
        return instance;
      }
      if (key.equals("txfailed")) {
        InnerTransactionResultResult instance = new InnerTransactionResultResult();
        instance.discriminant = discriminant;
        instance.results =
            XdrElement.jsonArrayToArray(
                (List<Object>) jsonMap.get("txfailed"),
                OperationResult.class,
                item -> OperationResult.fromJsonObject(item));
        return instance;
      }
      throw new IllegalArgumentException(
          "Unknown key '" + key + "' for InnerTransactionResultResult");
    }
  }

  /**
   * InnerTransactionResultExt's original definition in the XDR file is:
   *
   * <pre>
   * union switch (int v)
   *     {
   *     case 0:
   *         void;
   *     }
   * </pre>
   */
  @Data
  @NoArgsConstructor
  @AllArgsConstructor
  @Builder(toBuilder = true)
  public static class InnerTransactionResultExt implements XdrElement {
    private Integer discriminant;

    public void encode(XdrDataOutputStream stream) throws IOException {
      stream.writeInt(discriminant);
      switch (discriminant) {
        case 0:
          break;
      }
    }

    public static InnerTransactionResultExt decode(XdrDataInputStream stream, int maxDepth)
        throws IOException {
      if (maxDepth <= 0) {
        throw new IOException("Maximum decoding depth reached");
      }
      maxDepth -= 1;
      InnerTransactionResultExt decodedInnerTransactionResultExt = new InnerTransactionResultExt();
      Integer discriminant = stream.readInt();
      decodedInnerTransactionResultExt.setDiscriminant(discriminant);
      switch (decodedInnerTransactionResultExt.getDiscriminant()) {
        case 0:
          break;
        default:
          throw new IOException("Unknown discriminant value: " + discriminant);
      }
      return decodedInnerTransactionResultExt;
    }

    public static InnerTransactionResultExt decode(XdrDataInputStream stream) throws IOException {
      return decode(stream, XdrDataInputStream.DEFAULT_MAX_DEPTH);
    }

    public static InnerTransactionResultExt fromXdrBase64(String xdr) throws IOException {
      byte[] bytes = Base64Factory.getInstance().decode(xdr);
      return fromXdrByteArray(bytes);
    }

    public static InnerTransactionResultExt fromXdrByteArray(byte[] xdr) throws IOException {
      ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
      XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
      xdrDataInputStream.setMaxInputLen(xdr.length);
      return decode(xdrDataInputStream);
    }

    @Override
    public String toJson() {
      return XdrElement.gson.toJson(toJsonObject());
    }

    public static InnerTransactionResultExt fromJson(String json) {
      return fromJsonObject(XdrElement.gson.fromJson(json, Object.class));
    }

    Object toJsonObject() {
      if (discriminant == 0) {
        return "v0";
      }
      throw new IllegalArgumentException("Unknown discriminant: " + discriminant);
    }

    @SuppressWarnings("unchecked")
    static InnerTransactionResultExt fromJsonObject(Object json) {
      if (json instanceof String) {
        String strVal = (String) json;
        if (!(strVal.equals("v0"))) {
          throw new IllegalArgumentException(
              "Unexpected string '" + strVal + "' for InnerTransactionResultExt");
        }
        InnerTransactionResultExt instance = new InnerTransactionResultExt();
        instance.discriminant = Integer.parseInt(strVal.substring(1));
        return instance;
      }
      throw new IllegalArgumentException(
          "Expected a string for InnerTransactionResultExt, got: " + json);
    }
  }
}
