// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.LinkedHashMap;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.stellar.sdk.Base64Factory;

/**
 * InnerTransactionResultPair's original definition in the XDR file is:
 *
 * <pre>
 * struct InnerTransactionResultPair
 * {
 *     Hash transactionHash;          // hash of the inner transaction
 *     InnerTransactionResult result; // result for the inner transaction
 * };
 * </pre>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
public class InnerTransactionResultPair implements XdrElement {
  private Hash transactionHash;
  private InnerTransactionResult result;

  public void encode(XdrDataOutputStream stream) throws IOException {
    transactionHash.encode(stream);
    result.encode(stream);
  }

  public static InnerTransactionResultPair decode(XdrDataInputStream stream, int maxDepth)
      throws IOException {
    if (maxDepth <= 0) {
      throw new IOException("Maximum decoding depth reached");
    }
    maxDepth -= 1;
    InnerTransactionResultPair decodedInnerTransactionResultPair = new InnerTransactionResultPair();
    decodedInnerTransactionResultPair.transactionHash = Hash.decode(stream, maxDepth);
    decodedInnerTransactionResultPair.result = InnerTransactionResult.decode(stream, maxDepth);
    return decodedInnerTransactionResultPair;
  }

  public static InnerTransactionResultPair decode(XdrDataInputStream stream) throws IOException {
    return decode(stream, XdrDataInputStream.DEFAULT_MAX_DEPTH);
  }

  public static InnerTransactionResultPair fromXdrBase64(String xdr) throws IOException {
    byte[] bytes = Base64Factory.getInstance().decode(xdr);
    return fromXdrByteArray(bytes);
  }

  public static InnerTransactionResultPair fromXdrByteArray(byte[] xdr) throws IOException {
    ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
    XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
    xdrDataInputStream.setMaxInputLen(xdr.length);
    return decode(xdrDataInputStream);
  }

  @Override
  public String toJson() {
    return XdrElement.gson.toJson(toJsonObject());
  }

  public static InnerTransactionResultPair fromJson(String json) {
    return fromJsonObject(XdrElement.gson.fromJson(json, Object.class));
  }

  Object toJsonObject() {
    LinkedHashMap<String, Object> jsonMap = new LinkedHashMap<>();
    jsonMap.put("transaction_hash", transactionHash.toJsonObject());
    jsonMap.put("result", result.toJsonObject());
    return jsonMap;
  }

  @SuppressWarnings("unchecked")
  static InnerTransactionResultPair fromJsonObject(Object json) {
    java.util.Map<String, Object> jsonMap = (java.util.Map<String, Object>) json;
    InnerTransactionResultPair instance = new InnerTransactionResultPair();
    instance.transactionHash = Hash.fromJsonObject(jsonMap.get("transaction_hash"));
    instance.result = InnerTransactionResult.fromJsonObject(jsonMap.get("result"));
    return instance;
  }
}
