// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.stellar.sdk.Base64Factory;

/**
 * LedgerEntryChanges's original definition in the XDR file is:
 *
 * <pre>
 * typedef LedgerEntryChange LedgerEntryChanges&lt;&gt;;
 * </pre>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class LedgerEntryChanges implements XdrElement {
  private LedgerEntryChange[] LedgerEntryChanges;

  public void encode(XdrDataOutputStream stream) throws IOException {
    int LedgerEntryChangesSize = getLedgerEntryChanges().length;
    stream.writeInt(LedgerEntryChangesSize);
    for (int i = 0; i < LedgerEntryChangesSize; i++) {
      LedgerEntryChanges[i].encode(stream);
    }
  }

  public static LedgerEntryChanges decode(XdrDataInputStream stream) throws IOException {
    LedgerEntryChanges decodedLedgerEntryChanges = new LedgerEntryChanges();
    int LedgerEntryChangesSize = stream.readInt();
    decodedLedgerEntryChanges.LedgerEntryChanges = new LedgerEntryChange[LedgerEntryChangesSize];
    for (int i = 0; i < LedgerEntryChangesSize; i++) {
      decodedLedgerEntryChanges.LedgerEntryChanges[i] = LedgerEntryChange.decode(stream);
    }
    return decodedLedgerEntryChanges;
  }

  public static LedgerEntryChanges fromXdrBase64(String xdr) throws IOException {
    byte[] bytes = Base64Factory.getInstance().decode(xdr);
    return fromXdrByteArray(bytes);
  }

  public static LedgerEntryChanges fromXdrByteArray(byte[] xdr) throws IOException {
    ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
    XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
    return decode(xdrDataInputStream);
  }
}
