// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.LinkedHashMap;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.stellar.sdk.Base64Factory;

/**
 * LedgerHeaderHistoryEntry's original definition in the XDR file is:
 *
 * <pre>
 * struct LedgerHeaderHistoryEntry
 * {
 *     Hash hash;
 *     LedgerHeader header;
 *
 *     // reserved for future use
 *     union switch (int v)
 *     {
 *     case 0:
 *         void;
 *     }
 *     ext;
 * };
 * </pre>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
public class LedgerHeaderHistoryEntry implements XdrElement {
  private Hash hash;
  private LedgerHeader header;
  private LedgerHeaderHistoryEntryExt ext;

  public void encode(XdrDataOutputStream stream) throws IOException {
    hash.encode(stream);
    header.encode(stream);
    ext.encode(stream);
  }

  public static LedgerHeaderHistoryEntry decode(XdrDataInputStream stream, int maxDepth)
      throws IOException {
    if (maxDepth <= 0) {
      throw new IOException("Maximum decoding depth reached");
    }
    maxDepth -= 1;
    LedgerHeaderHistoryEntry decodedLedgerHeaderHistoryEntry = new LedgerHeaderHistoryEntry();
    decodedLedgerHeaderHistoryEntry.hash = Hash.decode(stream, maxDepth);
    decodedLedgerHeaderHistoryEntry.header = LedgerHeader.decode(stream, maxDepth);
    decodedLedgerHeaderHistoryEntry.ext = LedgerHeaderHistoryEntryExt.decode(stream, maxDepth);
    return decodedLedgerHeaderHistoryEntry;
  }

  public static LedgerHeaderHistoryEntry decode(XdrDataInputStream stream) throws IOException {
    return decode(stream, XdrDataInputStream.DEFAULT_MAX_DEPTH);
  }

  public static LedgerHeaderHistoryEntry fromXdrBase64(String xdr) throws IOException {
    byte[] bytes = Base64Factory.getInstance().decode(xdr);
    return fromXdrByteArray(bytes);
  }

  public static LedgerHeaderHistoryEntry fromXdrByteArray(byte[] xdr) throws IOException {
    ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
    XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
    xdrDataInputStream.setMaxInputLen(xdr.length);
    return decode(xdrDataInputStream);
  }

  @Override
  public String toJson() {
    return XdrElement.gson.toJson(toJsonObject());
  }

  public static LedgerHeaderHistoryEntry fromJson(String json) {
    return fromJsonObject(XdrElement.gson.fromJson(json, Object.class));
  }

  Object toJsonObject() {
    LinkedHashMap<String, Object> jsonMap = new LinkedHashMap<>();
    jsonMap.put("hash", hash.toJsonObject());
    jsonMap.put("header", header.toJsonObject());
    jsonMap.put("ext", ext.toJsonObject());
    return jsonMap;
  }

  @SuppressWarnings("unchecked")
  static LedgerHeaderHistoryEntry fromJsonObject(Object json) {
    java.util.Map<String, Object> jsonMap = (java.util.Map<String, Object>) json;
    LedgerHeaderHistoryEntry instance = new LedgerHeaderHistoryEntry();
    instance.hash = Hash.fromJsonObject(jsonMap.get("hash"));
    instance.header = LedgerHeader.fromJsonObject(jsonMap.get("header"));
    instance.ext = LedgerHeaderHistoryEntryExt.fromJsonObject(jsonMap.get("ext"));
    return instance;
  }

  /**
   * LedgerHeaderHistoryEntryExt's original definition in the XDR file is:
   *
   * <pre>
   * union switch (int v)
   *     {
   *     case 0:
   *         void;
   *     }
   * </pre>
   */
  @Data
  @NoArgsConstructor
  @AllArgsConstructor
  @Builder(toBuilder = true)
  public static class LedgerHeaderHistoryEntryExt implements XdrElement {
    private Integer discriminant;

    public void encode(XdrDataOutputStream stream) throws IOException {
      stream.writeInt(discriminant);
      switch (discriminant) {
        case 0:
          break;
      }
    }

    public static LedgerHeaderHistoryEntryExt decode(XdrDataInputStream stream, int maxDepth)
        throws IOException {
      if (maxDepth <= 0) {
        throw new IOException("Maximum decoding depth reached");
      }
      maxDepth -= 1;
      LedgerHeaderHistoryEntryExt decodedLedgerHeaderHistoryEntryExt =
          new LedgerHeaderHistoryEntryExt();
      Integer discriminant = stream.readInt();
      decodedLedgerHeaderHistoryEntryExt.setDiscriminant(discriminant);
      switch (decodedLedgerHeaderHistoryEntryExt.getDiscriminant()) {
        case 0:
          break;
        default:
          throw new IOException("Unknown discriminant value: " + discriminant);
      }
      return decodedLedgerHeaderHistoryEntryExt;
    }

    public static LedgerHeaderHistoryEntryExt decode(XdrDataInputStream stream) throws IOException {
      return decode(stream, XdrDataInputStream.DEFAULT_MAX_DEPTH);
    }

    public static LedgerHeaderHistoryEntryExt fromXdrBase64(String xdr) throws IOException {
      byte[] bytes = Base64Factory.getInstance().decode(xdr);
      return fromXdrByteArray(bytes);
    }

    public static LedgerHeaderHistoryEntryExt fromXdrByteArray(byte[] xdr) throws IOException {
      ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
      XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
      xdrDataInputStream.setMaxInputLen(xdr.length);
      return decode(xdrDataInputStream);
    }

    @Override
    public String toJson() {
      return XdrElement.gson.toJson(toJsonObject());
    }

    public static LedgerHeaderHistoryEntryExt fromJson(String json) {
      return fromJsonObject(XdrElement.gson.fromJson(json, Object.class));
    }

    Object toJsonObject() {
      if (discriminant == 0) {
        return "v0";
      }
      throw new IllegalArgumentException("Unknown discriminant: " + discriminant);
    }

    @SuppressWarnings("unchecked")
    static LedgerHeaderHistoryEntryExt fromJsonObject(Object json) {
      if (json instanceof String) {
        String strVal = (String) json;
        if (!(strVal.equals("v0"))) {
          throw new IllegalArgumentException(
              "Unexpected string '" + strVal + "' for LedgerHeaderHistoryEntryExt");
        }
        LedgerHeaderHistoryEntryExt instance = new LedgerHeaderHistoryEntryExt();
        instance.discriminant = Integer.parseInt(strVal.substring(1));
        return instance;
      }
      throw new IllegalArgumentException(
          "Expected a string for LedgerHeaderHistoryEntryExt, got: " + json);
    }
  }
}
