// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import org.stellar.sdk.Base64Factory;

/**
 * LedgerHeaderFlags's original definition in the XDR file is:
 *
 * <pre>
 * enum LedgerHeaderFlags
 * {
 *     DISABLE_LIQUIDITY_POOL_TRADING_FLAG = 0x1,
 *     DISABLE_LIQUIDITY_POOL_DEPOSIT_FLAG = 0x2,
 *     DISABLE_LIQUIDITY_POOL_WITHDRAWAL_FLAG = 0x4
 * };
 * </pre>
 */
public enum LedgerHeaderFlags implements XdrElement {
  DISABLE_LIQUIDITY_POOL_TRADING_FLAG(1),
  DISABLE_LIQUIDITY_POOL_DEPOSIT_FLAG(2),
  DISABLE_LIQUIDITY_POOL_WITHDRAWAL_FLAG(4);

  private final int value;

  LedgerHeaderFlags(int value) {
    this.value = value;
  }

  public int getValue() {
    return value;
  }

  public static LedgerHeaderFlags decode(XdrDataInputStream stream) throws IOException {
    int value = stream.readInt();
    switch (value) {
      case 1:
        return DISABLE_LIQUIDITY_POOL_TRADING_FLAG;
      case 2:
        return DISABLE_LIQUIDITY_POOL_DEPOSIT_FLAG;
      case 4:
        return DISABLE_LIQUIDITY_POOL_WITHDRAWAL_FLAG;
      default:
        throw new IllegalArgumentException("Unknown enum value: " + value);
    }
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    stream.writeInt(value);
  }

  public static LedgerHeaderFlags fromXdrBase64(String xdr) throws IOException {
    byte[] bytes = Base64Factory.getInstance().decode(xdr);
    return fromXdrByteArray(bytes);
  }

  public static LedgerHeaderFlags fromXdrByteArray(byte[] xdr) throws IOException {
    ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
    XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
    return decode(xdrDataInputStream);
  }
}
