// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;

import com.google.common.base.Objects;
import java.io.IOException;

// === xdr source ============================================================

//  struct OperationMeta
//  {
//      LedgerEntryChanges changes;
//  };

//  ===========================================================================
public class OperationMeta implements XdrElement {
  public OperationMeta() {}

  private LedgerEntryChanges changes;

  public LedgerEntryChanges getChanges() {
    return this.changes;
  }

  public void setChanges(LedgerEntryChanges value) {
    this.changes = value;
  }

  public static void encode(XdrDataOutputStream stream, OperationMeta encodedOperationMeta)
      throws IOException {
    LedgerEntryChanges.encode(stream, encodedOperationMeta.changes);
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }

  public static OperationMeta decode(XdrDataInputStream stream) throws IOException {
    OperationMeta decodedOperationMeta = new OperationMeta();
    decodedOperationMeta.changes = LedgerEntryChanges.decode(stream);
    return decodedOperationMeta;
  }

  @Override
  public int hashCode() {
    return Objects.hashCode(this.changes);
  }

  @Override
  public boolean equals(Object object) {
    if (!(object instanceof OperationMeta)) {
      return false;
    }

    OperationMeta other = (OperationMeta) object;
    return Objects.equal(this.changes, other.changes);
  }

  public static final class Builder {
    private LedgerEntryChanges changes;

    public Builder changes(LedgerEntryChanges changes) {
      this.changes = changes;
      return this;
    }

    public OperationMeta build() {
      OperationMeta val = new OperationMeta();
      val.setChanges(changes);
      return val;
    }
  }
}
