// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.LinkedHashMap;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.stellar.sdk.Base64Factory;

/**
 * PathPaymentStrictSendResult's original definition in the XDR file is:
 *
 * <pre>
 * union PathPaymentStrictSendResult switch (PathPaymentStrictSendResultCode code)
 * {
 * case PATH_PAYMENT_STRICT_SEND_SUCCESS:
 *     struct
 *     {
 *         ClaimAtom offers&lt;&gt;;
 *         SimplePaymentResult last;
 *     } success;
 * case PATH_PAYMENT_STRICT_SEND_MALFORMED:
 * case PATH_PAYMENT_STRICT_SEND_UNDERFUNDED:
 * case PATH_PAYMENT_STRICT_SEND_SRC_NO_TRUST:
 * case PATH_PAYMENT_STRICT_SEND_SRC_NOT_AUTHORIZED:
 * case PATH_PAYMENT_STRICT_SEND_NO_DESTINATION:
 * case PATH_PAYMENT_STRICT_SEND_NO_TRUST:
 * case PATH_PAYMENT_STRICT_SEND_NOT_AUTHORIZED:
 * case PATH_PAYMENT_STRICT_SEND_LINE_FULL:
 *     void;
 * case PATH_PAYMENT_STRICT_SEND_NO_ISSUER:
 *     Asset noIssuer; // the asset that caused the error
 * case PATH_PAYMENT_STRICT_SEND_TOO_FEW_OFFERS:
 * case PATH_PAYMENT_STRICT_SEND_OFFER_CROSS_SELF:
 * case PATH_PAYMENT_STRICT_SEND_UNDER_DESTMIN:
 *     void;
 * };
 * </pre>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
public class PathPaymentStrictSendResult implements XdrElement {
  private PathPaymentStrictSendResultCode discriminant;
  private PathPaymentStrictSendResultSuccess success;
  private Asset noIssuer;

  public void encode(XdrDataOutputStream stream) throws IOException {
    stream.writeInt(discriminant.getValue());
    switch (discriminant) {
      case PATH_PAYMENT_STRICT_SEND_SUCCESS:
        success.encode(stream);
        break;
      case PATH_PAYMENT_STRICT_SEND_MALFORMED:
      case PATH_PAYMENT_STRICT_SEND_UNDERFUNDED:
      case PATH_PAYMENT_STRICT_SEND_SRC_NO_TRUST:
      case PATH_PAYMENT_STRICT_SEND_SRC_NOT_AUTHORIZED:
      case PATH_PAYMENT_STRICT_SEND_NO_DESTINATION:
      case PATH_PAYMENT_STRICT_SEND_NO_TRUST:
      case PATH_PAYMENT_STRICT_SEND_NOT_AUTHORIZED:
      case PATH_PAYMENT_STRICT_SEND_LINE_FULL:
        break;
      case PATH_PAYMENT_STRICT_SEND_NO_ISSUER:
        noIssuer.encode(stream);
        break;
      case PATH_PAYMENT_STRICT_SEND_TOO_FEW_OFFERS:
      case PATH_PAYMENT_STRICT_SEND_OFFER_CROSS_SELF:
      case PATH_PAYMENT_STRICT_SEND_UNDER_DESTMIN:
        break;
    }
  }

  public static PathPaymentStrictSendResult decode(XdrDataInputStream stream, int maxDepth)
      throws IOException {
    if (maxDepth <= 0) {
      throw new IOException("Maximum decoding depth reached");
    }
    maxDepth -= 1;
    PathPaymentStrictSendResult decodedPathPaymentStrictSendResult =
        new PathPaymentStrictSendResult();
    PathPaymentStrictSendResultCode discriminant =
        PathPaymentStrictSendResultCode.decode(stream, maxDepth);
    decodedPathPaymentStrictSendResult.setDiscriminant(discriminant);
    switch (decodedPathPaymentStrictSendResult.getDiscriminant()) {
      case PATH_PAYMENT_STRICT_SEND_SUCCESS:
        decodedPathPaymentStrictSendResult.success =
            PathPaymentStrictSendResultSuccess.decode(stream, maxDepth);
        break;
      case PATH_PAYMENT_STRICT_SEND_MALFORMED:
      case PATH_PAYMENT_STRICT_SEND_UNDERFUNDED:
      case PATH_PAYMENT_STRICT_SEND_SRC_NO_TRUST:
      case PATH_PAYMENT_STRICT_SEND_SRC_NOT_AUTHORIZED:
      case PATH_PAYMENT_STRICT_SEND_NO_DESTINATION:
      case PATH_PAYMENT_STRICT_SEND_NO_TRUST:
      case PATH_PAYMENT_STRICT_SEND_NOT_AUTHORIZED:
      case PATH_PAYMENT_STRICT_SEND_LINE_FULL:
        break;
      case PATH_PAYMENT_STRICT_SEND_NO_ISSUER:
        decodedPathPaymentStrictSendResult.noIssuer = Asset.decode(stream, maxDepth);
        break;
      case PATH_PAYMENT_STRICT_SEND_TOO_FEW_OFFERS:
      case PATH_PAYMENT_STRICT_SEND_OFFER_CROSS_SELF:
      case PATH_PAYMENT_STRICT_SEND_UNDER_DESTMIN:
        break;
      default:
        throw new IOException("Unknown discriminant value: " + discriminant);
    }
    return decodedPathPaymentStrictSendResult;
  }

  public static PathPaymentStrictSendResult decode(XdrDataInputStream stream) throws IOException {
    return decode(stream, XdrDataInputStream.DEFAULT_MAX_DEPTH);
  }

  public static PathPaymentStrictSendResult fromXdrBase64(String xdr) throws IOException {
    byte[] bytes = Base64Factory.getInstance().decode(xdr);
    return fromXdrByteArray(bytes);
  }

  public static PathPaymentStrictSendResult fromXdrByteArray(byte[] xdr) throws IOException {
    ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
    XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
    xdrDataInputStream.setMaxInputLen(xdr.length);
    return decode(xdrDataInputStream);
  }

  @Override
  public String toJson() {
    return XdrElement.gson.toJson(toJsonObject());
  }

  public static PathPaymentStrictSendResult fromJson(String json) {
    return fromJsonObject(XdrElement.gson.fromJson(json, Object.class));
  }

  Object toJsonObject() {
    if (discriminant == PathPaymentStrictSendResultCode.PATH_PAYMENT_STRICT_SEND_SUCCESS) {
      LinkedHashMap<String, Object> jsonMap = new LinkedHashMap<>();
      jsonMap.put("success", success.toJsonObject());
      return jsonMap;
    }
    if (discriminant == PathPaymentStrictSendResultCode.PATH_PAYMENT_STRICT_SEND_MALFORMED) {
      return "malformed";
    }
    if (discriminant == PathPaymentStrictSendResultCode.PATH_PAYMENT_STRICT_SEND_UNDERFUNDED) {
      return "underfunded";
    }
    if (discriminant == PathPaymentStrictSendResultCode.PATH_PAYMENT_STRICT_SEND_SRC_NO_TRUST) {
      return "src_no_trust";
    }
    if (discriminant
        == PathPaymentStrictSendResultCode.PATH_PAYMENT_STRICT_SEND_SRC_NOT_AUTHORIZED) {
      return "src_not_authorized";
    }
    if (discriminant == PathPaymentStrictSendResultCode.PATH_PAYMENT_STRICT_SEND_NO_DESTINATION) {
      return "no_destination";
    }
    if (discriminant == PathPaymentStrictSendResultCode.PATH_PAYMENT_STRICT_SEND_NO_TRUST) {
      return "no_trust";
    }
    if (discriminant == PathPaymentStrictSendResultCode.PATH_PAYMENT_STRICT_SEND_NOT_AUTHORIZED) {
      return "not_authorized";
    }
    if (discriminant == PathPaymentStrictSendResultCode.PATH_PAYMENT_STRICT_SEND_LINE_FULL) {
      return "line_full";
    }
    if (discriminant == PathPaymentStrictSendResultCode.PATH_PAYMENT_STRICT_SEND_NO_ISSUER) {
      LinkedHashMap<String, Object> jsonMap = new LinkedHashMap<>();
      jsonMap.put("no_issuer", noIssuer.toJsonObject());
      return jsonMap;
    }
    if (discriminant == PathPaymentStrictSendResultCode.PATH_PAYMENT_STRICT_SEND_TOO_FEW_OFFERS) {
      return "too_few_offers";
    }
    if (discriminant == PathPaymentStrictSendResultCode.PATH_PAYMENT_STRICT_SEND_OFFER_CROSS_SELF) {
      return "offer_cross_self";
    }
    if (discriminant == PathPaymentStrictSendResultCode.PATH_PAYMENT_STRICT_SEND_UNDER_DESTMIN) {
      return "under_destmin";
    }
    throw new IllegalArgumentException("Unknown discriminant: " + discriminant);
  }

  @SuppressWarnings("unchecked")
  static PathPaymentStrictSendResult fromJsonObject(Object json) {
    if (json instanceof String) {
      String strVal = (String) json;
      if (!(strVal.equals("malformed")
          || strVal.equals("underfunded")
          || strVal.equals("src_no_trust")
          || strVal.equals("src_not_authorized")
          || strVal.equals("no_destination")
          || strVal.equals("no_trust")
          || strVal.equals("not_authorized")
          || strVal.equals("line_full")
          || strVal.equals("too_few_offers")
          || strVal.equals("offer_cross_self")
          || strVal.equals("under_destmin"))) {
        throw new IllegalArgumentException(
            "Unexpected string '" + strVal + "' for PathPaymentStrictSendResult");
      }
      PathPaymentStrictSendResult instance = new PathPaymentStrictSendResult();
      instance.discriminant = PathPaymentStrictSendResultCode.fromJsonObject(strVal);
      return instance;
    }
    java.util.Map<String, Object> jsonMap = (java.util.Map<String, Object>) json;
    if (jsonMap.containsKey("$schema")) {
      jsonMap = new LinkedHashMap<>(jsonMap);
      jsonMap.remove("$schema");
    }
    if (jsonMap.size() != 1) {
      throw new IllegalArgumentException(
          "Expected a single-key object for PathPaymentStrictSendResult, got: " + json);
    }
    String key = jsonMap.keySet().iterator().next();
    PathPaymentStrictSendResultCode discriminant =
        PathPaymentStrictSendResultCode.fromJsonObject(key);
    if (key.equals("success")) {
      PathPaymentStrictSendResult instance = new PathPaymentStrictSendResult();
      instance.discriminant = discriminant;
      instance.success = PathPaymentStrictSendResultSuccess.fromJsonObject(jsonMap.get("success"));
      return instance;
    }
    if (key.equals("no_issuer")) {
      PathPaymentStrictSendResult instance = new PathPaymentStrictSendResult();
      instance.discriminant = discriminant;
      instance.noIssuer = Asset.fromJsonObject(jsonMap.get("no_issuer"));
      return instance;
    }
    throw new IllegalArgumentException("Unknown key '" + key + "' for PathPaymentStrictSendResult");
  }

  /**
   * PathPaymentStrictSendResultSuccess's original definition in the XDR file is:
   *
   * <pre>
   * struct
   *     {
   *         ClaimAtom offers&lt;&gt;;
   *         SimplePaymentResult last;
   *     }
   * </pre>
   */
  @Data
  @NoArgsConstructor
  @AllArgsConstructor
  @Builder(toBuilder = true)
  public static class PathPaymentStrictSendResultSuccess implements XdrElement {
    private ClaimAtom[] offers;
    private SimplePaymentResult last;

    public void encode(XdrDataOutputStream stream) throws IOException {
      int offersSize = getOffers().length;
      stream.writeInt(offersSize);
      for (int i = 0; i < offersSize; i++) {
        offers[i].encode(stream);
      }
      last.encode(stream);
    }

    public static PathPaymentStrictSendResultSuccess decode(XdrDataInputStream stream, int maxDepth)
        throws IOException {
      if (maxDepth <= 0) {
        throw new IOException("Maximum decoding depth reached");
      }
      maxDepth -= 1;
      PathPaymentStrictSendResultSuccess decodedPathPaymentStrictSendResultSuccess =
          new PathPaymentStrictSendResultSuccess();
      int offersSize = stream.readInt();
      if (offersSize < 0) {
        throw new IOException("offers size " + offersSize + " is negative");
      }
      int offersRemainingInputLen = stream.getRemainingInputLen();
      if (offersRemainingInputLen >= 0 && offersRemainingInputLen < offersSize) {
        throw new IOException(
            "offers size "
                + offersSize
                + " exceeds remaining input length "
                + offersRemainingInputLen);
      }
      decodedPathPaymentStrictSendResultSuccess.offers = new ClaimAtom[offersSize];
      for (int i = 0; i < offersSize; i++) {
        decodedPathPaymentStrictSendResultSuccess.offers[i] = ClaimAtom.decode(stream, maxDepth);
      }
      decodedPathPaymentStrictSendResultSuccess.last = SimplePaymentResult.decode(stream, maxDepth);
      return decodedPathPaymentStrictSendResultSuccess;
    }

    public static PathPaymentStrictSendResultSuccess decode(XdrDataInputStream stream)
        throws IOException {
      return decode(stream, XdrDataInputStream.DEFAULT_MAX_DEPTH);
    }

    public static PathPaymentStrictSendResultSuccess fromXdrBase64(String xdr) throws IOException {
      byte[] bytes = Base64Factory.getInstance().decode(xdr);
      return fromXdrByteArray(bytes);
    }

    public static PathPaymentStrictSendResultSuccess fromXdrByteArray(byte[] xdr)
        throws IOException {
      ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
      XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
      xdrDataInputStream.setMaxInputLen(xdr.length);
      return decode(xdrDataInputStream);
    }

    @Override
    public String toJson() {
      return XdrElement.gson.toJson(toJsonObject());
    }

    public static PathPaymentStrictSendResultSuccess fromJson(String json) {
      return fromJsonObject(XdrElement.gson.fromJson(json, Object.class));
    }

    Object toJsonObject() {
      LinkedHashMap<String, Object> jsonMap = new LinkedHashMap<>();
      jsonMap.put("offers", XdrElement.arrayToJsonArray(offers, i -> offers[i].toJsonObject()));
      jsonMap.put("last", last.toJsonObject());
      return jsonMap;
    }

    @SuppressWarnings("unchecked")
    static PathPaymentStrictSendResultSuccess fromJsonObject(Object json) {
      java.util.Map<String, Object> jsonMap = (java.util.Map<String, Object>) json;
      PathPaymentStrictSendResultSuccess instance = new PathPaymentStrictSendResultSuccess();
      instance.offers =
          XdrElement.jsonArrayToArray(
              (List<Object>) jsonMap.get("offers"),
              ClaimAtom.class,
              item -> ClaimAtom.fromJsonObject(item));
      instance.last = SimplePaymentResult.fromJsonObject(jsonMap.get("last"));
      return instance;
    }
  }
}
