// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.stellar.sdk.Base64Factory;

/**
 * PersistedSCPState's original definition in the XDR file is:
 *
 * <pre>
 * union PersistedSCPState switch (int v)
 * {
 * case 0:
 * 	PersistedSCPStateV0 v0;
 * case 1:
 * 	PersistedSCPStateV1 v1;
 * };
 * </pre>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
public class PersistedSCPState implements XdrElement {
  private Integer discriminant;
  private PersistedSCPStateV0 v0;
  private PersistedSCPStateV1 v1;

  public void encode(XdrDataOutputStream stream) throws IOException {
    stream.writeInt(discriminant);
    switch (discriminant) {
      case 0:
        v0.encode(stream);
        break;
      case 1:
        v1.encode(stream);
        break;
    }
  }

  public static PersistedSCPState decode(XdrDataInputStream stream) throws IOException {
    PersistedSCPState decodedPersistedSCPState = new PersistedSCPState();
    Integer discriminant = stream.readInt();
    decodedPersistedSCPState.setDiscriminant(discriminant);
    switch (decodedPersistedSCPState.getDiscriminant()) {
      case 0:
        decodedPersistedSCPState.v0 = PersistedSCPStateV0.decode(stream);
        break;
      case 1:
        decodedPersistedSCPState.v1 = PersistedSCPStateV1.decode(stream);
        break;
    }
    return decodedPersistedSCPState;
  }

  public static PersistedSCPState fromXdrBase64(String xdr) throws IOException {
    byte[] bytes = Base64Factory.getInstance().decode(xdr);
    return fromXdrByteArray(bytes);
  }

  public static PersistedSCPState fromXdrByteArray(byte[] xdr) throws IOException {
    ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
    XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
    return decode(xdrDataInputStream);
  }
}
