// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;


import java.io.IOException;

// === xdr source ============================================================

//  enum PublicKeyType
//  {
//      PUBLIC_KEY_TYPE_ED25519 = KEY_TYPE_ED25519
//  };

//  ===========================================================================
public enum PublicKeyType  {
  PUBLIC_KEY_TYPE_ED25519(0),
  ;
  private int mValue;

  PublicKeyType(int value) {
      mValue = value;
  }

  public int getValue() {
      return mValue;
  }

  static PublicKeyType decode(XdrDataInputStream stream) throws IOException {
    int value = stream.readInt();
    switch (value) {
      case 0: return PUBLIC_KEY_TYPE_ED25519;
      default:
        throw new RuntimeException("Unknown enum value: " + value);
    }
  }

  static void encode(XdrDataOutputStream stream, PublicKeyType value) throws IOException {
    stream.writeInt(value.getValue());
  }
}
