// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;

import static org.stellar.sdk.xdr.Constants.*;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.Objects;
import org.stellar.sdk.Base64Factory;

// === xdr source ============================================================

//  union RestoreFootprintResult switch (RestoreFootprintResultCode code)
//  {
//  case RESTORE_FOOTPRINT_SUCCESS:
//      void;
//  case RESTORE_FOOTPRINT_MALFORMED:
//  case RESTORE_FOOTPRINT_RESOURCE_LIMIT_EXCEEDED:
//  case RESTORE_FOOTPRINT_INSUFFICIENT_REFUNDABLE_FEE:
//      void;
//  };

//  ===========================================================================
public class RestoreFootprintResult implements XdrElement {
  public RestoreFootprintResult() {}

  RestoreFootprintResultCode code;

  public RestoreFootprintResultCode getDiscriminant() {
    return this.code;
  }

  public void setDiscriminant(RestoreFootprintResultCode value) {
    this.code = value;
  }

  public static final class Builder {
    private RestoreFootprintResultCode discriminant;

    public Builder discriminant(RestoreFootprintResultCode discriminant) {
      this.discriminant = discriminant;
      return this;
    }

    public RestoreFootprintResult build() {
      RestoreFootprintResult val = new RestoreFootprintResult();
      val.setDiscriminant(discriminant);
      return val;
    }
  }

  public static void encode(
      XdrDataOutputStream stream, RestoreFootprintResult encodedRestoreFootprintResult)
      throws IOException {
    // Xdrgen::AST::Identifier
    // RestoreFootprintResultCode
    stream.writeInt(encodedRestoreFootprintResult.getDiscriminant().getValue());
    switch (encodedRestoreFootprintResult.getDiscriminant()) {
      case RESTORE_FOOTPRINT_SUCCESS:
        break;
      case RESTORE_FOOTPRINT_MALFORMED:
      case RESTORE_FOOTPRINT_RESOURCE_LIMIT_EXCEEDED:
      case RESTORE_FOOTPRINT_INSUFFICIENT_REFUNDABLE_FEE:
        break;
    }
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }

  public static RestoreFootprintResult decode(XdrDataInputStream stream) throws IOException {
    RestoreFootprintResult decodedRestoreFootprintResult = new RestoreFootprintResult();
    RestoreFootprintResultCode discriminant = RestoreFootprintResultCode.decode(stream);
    decodedRestoreFootprintResult.setDiscriminant(discriminant);
    switch (decodedRestoreFootprintResult.getDiscriminant()) {
      case RESTORE_FOOTPRINT_SUCCESS:
        break;
      case RESTORE_FOOTPRINT_MALFORMED:
      case RESTORE_FOOTPRINT_RESOURCE_LIMIT_EXCEEDED:
      case RESTORE_FOOTPRINT_INSUFFICIENT_REFUNDABLE_FEE:
        break;
    }
    return decodedRestoreFootprintResult;
  }

  @Override
  public int hashCode() {
    return Objects.hash(this.code);
  }

  @Override
  public boolean equals(Object object) {
    if (!(object instanceof RestoreFootprintResult)) {
      return false;
    }

    RestoreFootprintResult other = (RestoreFootprintResult) object;
    return Objects.equals(this.code, other.code);
  }

  @Override
  public String toXdrBase64() throws IOException {
    return Base64Factory.getInstance().encodeToString(toXdrByteArray());
  }

  @Override
  public byte[] toXdrByteArray() throws IOException {
    ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
    XdrDataOutputStream xdrDataOutputStream = new XdrDataOutputStream(byteArrayOutputStream);
    encode(xdrDataOutputStream);
    return byteArrayOutputStream.toByteArray();
  }

  public static RestoreFootprintResult fromXdrBase64(String xdr) throws IOException {
    byte[] bytes = Base64Factory.getInstance().decode(xdr);
    return fromXdrByteArray(bytes);
  }

  public static RestoreFootprintResult fromXdrByteArray(byte[] xdr) throws IOException {
    ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
    XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
    return decode(xdrDataInputStream);
  }
}
