// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.stellar.sdk.Base64Factory;

/**
 * RevokeSponsorshipResult's original definition in the XDR file is:
 *
 * <pre>
 * union RevokeSponsorshipResult switch (RevokeSponsorshipResultCode code)
 * {
 * case REVOKE_SPONSORSHIP_SUCCESS:
 *     void;
 * case REVOKE_SPONSORSHIP_DOES_NOT_EXIST:
 * case REVOKE_SPONSORSHIP_NOT_SPONSOR:
 * case REVOKE_SPONSORSHIP_LOW_RESERVE:
 * case REVOKE_SPONSORSHIP_ONLY_TRANSFERABLE:
 * case REVOKE_SPONSORSHIP_MALFORMED:
 *     void;
 * };
 * </pre>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
public class RevokeSponsorshipResult implements XdrElement {
  private RevokeSponsorshipResultCode discriminant;

  public void encode(XdrDataOutputStream stream) throws IOException {
    stream.writeInt(discriminant.getValue());
    switch (discriminant) {
      case REVOKE_SPONSORSHIP_SUCCESS:
        break;
      case REVOKE_SPONSORSHIP_DOES_NOT_EXIST:
      case REVOKE_SPONSORSHIP_NOT_SPONSOR:
      case REVOKE_SPONSORSHIP_LOW_RESERVE:
      case REVOKE_SPONSORSHIP_ONLY_TRANSFERABLE:
      case REVOKE_SPONSORSHIP_MALFORMED:
        break;
    }
  }

  public static RevokeSponsorshipResult decode(XdrDataInputStream stream, int maxDepth)
      throws IOException {
    if (maxDepth <= 0) {
      throw new IOException("Maximum decoding depth reached");
    }
    maxDepth -= 1;
    RevokeSponsorshipResult decodedRevokeSponsorshipResult = new RevokeSponsorshipResult();
    RevokeSponsorshipResultCode discriminant = RevokeSponsorshipResultCode.decode(stream, maxDepth);
    decodedRevokeSponsorshipResult.setDiscriminant(discriminant);
    switch (decodedRevokeSponsorshipResult.getDiscriminant()) {
      case REVOKE_SPONSORSHIP_SUCCESS:
        break;
      case REVOKE_SPONSORSHIP_DOES_NOT_EXIST:
      case REVOKE_SPONSORSHIP_NOT_SPONSOR:
      case REVOKE_SPONSORSHIP_LOW_RESERVE:
      case REVOKE_SPONSORSHIP_ONLY_TRANSFERABLE:
      case REVOKE_SPONSORSHIP_MALFORMED:
        break;
      default:
        throw new IOException("Unknown discriminant value: " + discriminant);
    }
    return decodedRevokeSponsorshipResult;
  }

  public static RevokeSponsorshipResult decode(XdrDataInputStream stream) throws IOException {
    return decode(stream, XdrDataInputStream.DEFAULT_MAX_DEPTH);
  }

  public static RevokeSponsorshipResult fromXdrBase64(String xdr) throws IOException {
    byte[] bytes = Base64Factory.getInstance().decode(xdr);
    return fromXdrByteArray(bytes);
  }

  public static RevokeSponsorshipResult fromXdrByteArray(byte[] xdr) throws IOException {
    ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
    XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
    xdrDataInputStream.setMaxInputLen(xdr.length);
    return decode(xdrDataInputStream);
  }

  @Override
  public String toJson() {
    return XdrElement.gson.toJson(toJsonObject());
  }

  public static RevokeSponsorshipResult fromJson(String json) {
    return fromJsonObject(XdrElement.gson.fromJson(json, Object.class));
  }

  Object toJsonObject() {
    if (discriminant == RevokeSponsorshipResultCode.REVOKE_SPONSORSHIP_SUCCESS) {
      return "success";
    }
    if (discriminant == RevokeSponsorshipResultCode.REVOKE_SPONSORSHIP_DOES_NOT_EXIST) {
      return "does_not_exist";
    }
    if (discriminant == RevokeSponsorshipResultCode.REVOKE_SPONSORSHIP_NOT_SPONSOR) {
      return "not_sponsor";
    }
    if (discriminant == RevokeSponsorshipResultCode.REVOKE_SPONSORSHIP_LOW_RESERVE) {
      return "low_reserve";
    }
    if (discriminant == RevokeSponsorshipResultCode.REVOKE_SPONSORSHIP_ONLY_TRANSFERABLE) {
      return "only_transferable";
    }
    if (discriminant == RevokeSponsorshipResultCode.REVOKE_SPONSORSHIP_MALFORMED) {
      return "malformed";
    }
    throw new IllegalArgumentException("Unknown discriminant: " + discriminant);
  }

  @SuppressWarnings("unchecked")
  static RevokeSponsorshipResult fromJsonObject(Object json) {
    if (json instanceof String) {
      String strVal = (String) json;
      if (!(strVal.equals("success")
          || strVal.equals("does_not_exist")
          || strVal.equals("not_sponsor")
          || strVal.equals("low_reserve")
          || strVal.equals("only_transferable")
          || strVal.equals("malformed"))) {
        throw new IllegalArgumentException(
            "Unexpected string '" + strVal + "' for RevokeSponsorshipResult");
      }
      RevokeSponsorshipResult instance = new RevokeSponsorshipResult();
      instance.discriminant = RevokeSponsorshipResultCode.fromJsonObject(strVal);
      return instance;
    }
    throw new IllegalArgumentException(
        "Expected a string for RevokeSponsorshipResult, got: " + json);
  }
}
