// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.LinkedHashMap;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.stellar.sdk.Base64Factory;

/**
 * SCSpecTypeResult's original definition in the XDR file is:
 *
 * <pre>
 * struct SCSpecTypeResult
 * {
 *     SCSpecTypeDef okType;
 *     SCSpecTypeDef errorType;
 * };
 * </pre>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
public class SCSpecTypeResult implements XdrElement {
  private SCSpecTypeDef okType;
  private SCSpecTypeDef errorType;

  public void encode(XdrDataOutputStream stream) throws IOException {
    okType.encode(stream);
    errorType.encode(stream);
  }

  public static SCSpecTypeResult decode(XdrDataInputStream stream, int maxDepth)
      throws IOException {
    if (maxDepth <= 0) {
      throw new IOException("Maximum decoding depth reached");
    }
    maxDepth -= 1;
    SCSpecTypeResult decodedSCSpecTypeResult = new SCSpecTypeResult();
    decodedSCSpecTypeResult.okType = SCSpecTypeDef.decode(stream, maxDepth);
    decodedSCSpecTypeResult.errorType = SCSpecTypeDef.decode(stream, maxDepth);
    return decodedSCSpecTypeResult;
  }

  public static SCSpecTypeResult decode(XdrDataInputStream stream) throws IOException {
    return decode(stream, XdrDataInputStream.DEFAULT_MAX_DEPTH);
  }

  public static SCSpecTypeResult fromXdrBase64(String xdr) throws IOException {
    byte[] bytes = Base64Factory.getInstance().decode(xdr);
    return fromXdrByteArray(bytes);
  }

  public static SCSpecTypeResult fromXdrByteArray(byte[] xdr) throws IOException {
    ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
    XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
    xdrDataInputStream.setMaxInputLen(xdr.length);
    return decode(xdrDataInputStream);
  }

  @Override
  public String toJson() {
    return XdrElement.gson.toJson(toJsonObject());
  }

  public static SCSpecTypeResult fromJson(String json) {
    return fromJsonObject(XdrElement.gson.fromJson(json, Object.class));
  }

  Object toJsonObject() {
    LinkedHashMap<String, Object> jsonMap = new LinkedHashMap<>();
    jsonMap.put("ok_type", okType.toJsonObject());
    jsonMap.put("error_type", errorType.toJsonObject());
    return jsonMap;
  }

  @SuppressWarnings("unchecked")
  static SCSpecTypeResult fromJsonObject(Object json) {
    java.util.Map<String, Object> jsonMap = (java.util.Map<String, Object>) json;
    SCSpecTypeResult instance = new SCSpecTypeResult();
    instance.okType = SCSpecTypeDef.fromJsonObject(jsonMap.get("ok_type"));
    instance.errorType = SCSpecTypeDef.fromJsonObject(jsonMap.get("error_type"));
    return instance;
  }
}
