// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.stellar.sdk.Base64Factory;

/**
 * SCSpecTypeBytesN's original definition in the XDR file is:
 *
 * <pre>
 * struct SCSpecTypeBytesN
 * {
 *     uint32 n;
 * };
 * </pre>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
public class SCSpecTypeBytesN implements XdrElement {
  private Uint32 n;

  public void encode(XdrDataOutputStream stream) throws IOException {
    n.encode(stream);
  }

  public static SCSpecTypeBytesN decode(XdrDataInputStream stream) throws IOException {
    SCSpecTypeBytesN decodedSCSpecTypeBytesN = new SCSpecTypeBytesN();
    decodedSCSpecTypeBytesN.n = Uint32.decode(stream);
    return decodedSCSpecTypeBytesN;
  }

  public static SCSpecTypeBytesN fromXdrBase64(String xdr) throws IOException {
    byte[] bytes = Base64Factory.getInstance().decode(xdr);
    return fromXdrByteArray(bytes);
  }

  public static SCSpecTypeBytesN fromXdrByteArray(byte[] xdr) throws IOException {
    ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
    XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
    return decode(xdrDataInputStream);
  }
}
