// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.stellar.sdk.Base64Factory;

/**
 * SorobanAuthorizedFunction's original definition in the XDR file is:
 *
 * <pre>
 * union SorobanAuthorizedFunction switch (SorobanAuthorizedFunctionType type)
 * {
 * case SOROBAN_AUTHORIZED_FUNCTION_TYPE_CONTRACT_FN:
 *     InvokeContractArgs contractFn;
 * case SOROBAN_AUTHORIZED_FUNCTION_TYPE_CREATE_CONTRACT_HOST_FN:
 *     CreateContractArgs createContractHostFn;
 * };
 * </pre>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
public class SorobanAuthorizedFunction implements XdrElement {
  private SorobanAuthorizedFunctionType discriminant;
  private InvokeContractArgs contractFn;
  private CreateContractArgs createContractHostFn;

  public void encode(XdrDataOutputStream stream) throws IOException {
    stream.writeInt(discriminant.getValue());
    switch (discriminant) {
      case SOROBAN_AUTHORIZED_FUNCTION_TYPE_CONTRACT_FN:
        contractFn.encode(stream);
        break;
      case SOROBAN_AUTHORIZED_FUNCTION_TYPE_CREATE_CONTRACT_HOST_FN:
        createContractHostFn.encode(stream);
        break;
    }
  }

  public static SorobanAuthorizedFunction decode(XdrDataInputStream stream) throws IOException {
    SorobanAuthorizedFunction decodedSorobanAuthorizedFunction = new SorobanAuthorizedFunction();
    SorobanAuthorizedFunctionType discriminant = SorobanAuthorizedFunctionType.decode(stream);
    decodedSorobanAuthorizedFunction.setDiscriminant(discriminant);
    switch (decodedSorobanAuthorizedFunction.getDiscriminant()) {
      case SOROBAN_AUTHORIZED_FUNCTION_TYPE_CONTRACT_FN:
        decodedSorobanAuthorizedFunction.contractFn = InvokeContractArgs.decode(stream);
        break;
      case SOROBAN_AUTHORIZED_FUNCTION_TYPE_CREATE_CONTRACT_HOST_FN:
        decodedSorobanAuthorizedFunction.createContractHostFn = CreateContractArgs.decode(stream);
        break;
    }
    return decodedSorobanAuthorizedFunction;
  }

  public static SorobanAuthorizedFunction fromXdrBase64(String xdr) throws IOException {
    byte[] bytes = Base64Factory.getInstance().decode(xdr);
    return fromXdrByteArray(bytes);
  }

  public static SorobanAuthorizedFunction fromXdrByteArray(byte[] xdr) throws IOException {
    ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
    XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
    return decode(xdrDataInputStream);
  }
}
