// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.stellar.sdk.Base64Factory;

/**
 * SorobanTransactionData's original definition in the XDR file is:
 *
 * <pre>
 * struct SorobanTransactionData
 * {
 *     union switch (int v)
 *     {
 *     case 0:
 *         void;
 *     case 1:
 *         SorobanResourcesExtV0 resourceExt;
 *     } ext;
 *     SorobanResources resources;
 *     // Amount of the transaction `fee` allocated to the Soroban resource fees.
 *     // The fraction of `resourceFee` corresponding to `resources` specified
 *     // above is &#42;not&#42; refundable (i.e. fees for instructions, ledger I/O), as
 *     // well as fees for the transaction size.
 *     // The remaining part of the fee is refundable and the charged value is
 *     // based on the actual consumption of refundable resources (events, ledger
 *     // rent bumps).
 *     // The `inclusionFee` used for prioritization of the transaction is defined
 *     // as `tx.fee - resourceFee`.
 *     int64 resourceFee;
 * };
 * </pre>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
public class SorobanTransactionData implements XdrElement {
  private SorobanTransactionDataExt ext;
  private SorobanResources resources;
  private Int64 resourceFee;

  public void encode(XdrDataOutputStream stream) throws IOException {
    ext.encode(stream);
    resources.encode(stream);
    resourceFee.encode(stream);
  }

  public static SorobanTransactionData decode(XdrDataInputStream stream, int maxDepth)
      throws IOException {
    if (maxDepth <= 0) {
      throw new IOException("Maximum decoding depth reached");
    }
    maxDepth -= 1;
    SorobanTransactionData decodedSorobanTransactionData = new SorobanTransactionData();
    decodedSorobanTransactionData.ext = SorobanTransactionDataExt.decode(stream, maxDepth);
    decodedSorobanTransactionData.resources = SorobanResources.decode(stream, maxDepth);
    decodedSorobanTransactionData.resourceFee = Int64.decode(stream, maxDepth);
    return decodedSorobanTransactionData;
  }

  public static SorobanTransactionData decode(XdrDataInputStream stream) throws IOException {
    return decode(stream, XdrDataInputStream.DEFAULT_MAX_DEPTH);
  }

  public static SorobanTransactionData fromXdrBase64(String xdr) throws IOException {
    byte[] bytes = Base64Factory.getInstance().decode(xdr);
    return fromXdrByteArray(bytes);
  }

  public static SorobanTransactionData fromXdrByteArray(byte[] xdr) throws IOException {
    ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
    XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
    xdrDataInputStream.setMaxInputLen(xdr.length);
    return decode(xdrDataInputStream);
  }

  /**
   * SorobanTransactionDataExt's original definition in the XDR file is:
   *
   * <pre>
   * union switch (int v)
   *     {
   *     case 0:
   *         void;
   *     case 1:
   *         SorobanResourcesExtV0 resourceExt;
   *     }
   * </pre>
   */
  @Data
  @NoArgsConstructor
  @AllArgsConstructor
  @Builder(toBuilder = true)
  public static class SorobanTransactionDataExt implements XdrElement {
    private Integer discriminant;
    private SorobanResourcesExtV0 resourceExt;

    public void encode(XdrDataOutputStream stream) throws IOException {
      stream.writeInt(discriminant);
      switch (discriminant) {
        case 0:
          break;
        case 1:
          resourceExt.encode(stream);
          break;
      }
    }

    public static SorobanTransactionDataExt decode(XdrDataInputStream stream, int maxDepth)
        throws IOException {
      if (maxDepth <= 0) {
        throw new IOException("Maximum decoding depth reached");
      }
      maxDepth -= 1;
      SorobanTransactionDataExt decodedSorobanTransactionDataExt = new SorobanTransactionDataExt();
      Integer discriminant = stream.readInt();
      decodedSorobanTransactionDataExt.setDiscriminant(discriminant);
      switch (decodedSorobanTransactionDataExt.getDiscriminant()) {
        case 0:
          break;
        case 1:
          decodedSorobanTransactionDataExt.resourceExt =
              SorobanResourcesExtV0.decode(stream, maxDepth);
          break;
        default:
          throw new IOException("Unknown discriminant value: " + discriminant);
      }
      return decodedSorobanTransactionDataExt;
    }

    public static SorobanTransactionDataExt decode(XdrDataInputStream stream) throws IOException {
      return decode(stream, XdrDataInputStream.DEFAULT_MAX_DEPTH);
    }

    public static SorobanTransactionDataExt fromXdrBase64(String xdr) throws IOException {
      byte[] bytes = Base64Factory.getInstance().decode(xdr);
      return fromXdrByteArray(bytes);
    }

    public static SorobanTransactionDataExt fromXdrByteArray(byte[] xdr) throws IOException {
      ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
      XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
      xdrDataInputStream.setMaxInputLen(xdr.length);
      return decode(xdrDataInputStream);
    }
  }
}
