// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;

import static org.stellar.sdk.xdr.Constants.*;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.stellar.sdk.Base64Factory;

/**
 * SurveyResponseMessage's original definition in the XDR file is:
 *
 * <pre>
 * struct SurveyResponseMessage
 * {
 *     NodeID surveyorPeerID;
 *     NodeID surveyedPeerID;
 *     uint32 ledgerNum;
 *     SurveyMessageCommandType commandType;
 *     EncryptedBody encryptedBody;
 * };
 * </pre>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
public class SurveyResponseMessage implements XdrElement {
  private NodeID surveyorPeerID;
  private NodeID surveyedPeerID;
  private Uint32 ledgerNum;
  private SurveyMessageCommandType commandType;
  private EncryptedBody encryptedBody;

  public static void encode(
      XdrDataOutputStream stream, SurveyResponseMessage encodedSurveyResponseMessage)
      throws IOException {
    NodeID.encode(stream, encodedSurveyResponseMessage.surveyorPeerID);
    NodeID.encode(stream, encodedSurveyResponseMessage.surveyedPeerID);
    Uint32.encode(stream, encodedSurveyResponseMessage.ledgerNum);
    SurveyMessageCommandType.encode(stream, encodedSurveyResponseMessage.commandType);
    EncryptedBody.encode(stream, encodedSurveyResponseMessage.encryptedBody);
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }

  public static SurveyResponseMessage decode(XdrDataInputStream stream) throws IOException {
    SurveyResponseMessage decodedSurveyResponseMessage = new SurveyResponseMessage();
    decodedSurveyResponseMessage.surveyorPeerID = NodeID.decode(stream);
    decodedSurveyResponseMessage.surveyedPeerID = NodeID.decode(stream);
    decodedSurveyResponseMessage.ledgerNum = Uint32.decode(stream);
    decodedSurveyResponseMessage.commandType = SurveyMessageCommandType.decode(stream);
    decodedSurveyResponseMessage.encryptedBody = EncryptedBody.decode(stream);
    return decodedSurveyResponseMessage;
  }

  @Override
  public String toXdrBase64() throws IOException {
    return Base64Factory.getInstance().encodeToString(toXdrByteArray());
  }

  @Override
  public byte[] toXdrByteArray() throws IOException {
    ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
    XdrDataOutputStream xdrDataOutputStream = new XdrDataOutputStream(byteArrayOutputStream);
    encode(xdrDataOutputStream);
    return byteArrayOutputStream.toByteArray();
  }

  public static SurveyResponseMessage fromXdrBase64(String xdr) throws IOException {
    byte[] bytes = Base64Factory.getInstance().decode(xdr);
    return fromXdrByteArray(bytes);
  }

  public static SurveyResponseMessage fromXdrByteArray(byte[] xdr) throws IOException {
    ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
    XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
    return decode(xdrDataInputStream);
  }
}
