// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;

import static org.stellar.sdk.xdr.Constants.*;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.stellar.sdk.Base64Factory;

/**
 * SurveyRequestMessage's original definition in the XDR file is:
 *
 * <pre>
 * struct SurveyRequestMessage
 * {
 *     NodeID surveyorPeerID;
 *     NodeID surveyedPeerID;
 *     uint32 ledgerNum;
 *     Curve25519Public encryptionKey;
 *     SurveyMessageCommandType commandType;
 * };
 * </pre>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
public class SurveyRequestMessage implements XdrElement {
  private NodeID surveyorPeerID;
  private NodeID surveyedPeerID;
  private Uint32 ledgerNum;
  private Curve25519Public encryptionKey;
  private SurveyMessageCommandType commandType;

  public static void encode(
      XdrDataOutputStream stream, SurveyRequestMessage encodedSurveyRequestMessage)
      throws IOException {
    NodeID.encode(stream, encodedSurveyRequestMessage.surveyorPeerID);
    NodeID.encode(stream, encodedSurveyRequestMessage.surveyedPeerID);
    Uint32.encode(stream, encodedSurveyRequestMessage.ledgerNum);
    Curve25519Public.encode(stream, encodedSurveyRequestMessage.encryptionKey);
    SurveyMessageCommandType.encode(stream, encodedSurveyRequestMessage.commandType);
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }

  public static SurveyRequestMessage decode(XdrDataInputStream stream) throws IOException {
    SurveyRequestMessage decodedSurveyRequestMessage = new SurveyRequestMessage();
    decodedSurveyRequestMessage.surveyorPeerID = NodeID.decode(stream);
    decodedSurveyRequestMessage.surveyedPeerID = NodeID.decode(stream);
    decodedSurveyRequestMessage.ledgerNum = Uint32.decode(stream);
    decodedSurveyRequestMessage.encryptionKey = Curve25519Public.decode(stream);
    decodedSurveyRequestMessage.commandType = SurveyMessageCommandType.decode(stream);
    return decodedSurveyRequestMessage;
  }

  @Override
  public String toXdrBase64() throws IOException {
    return Base64Factory.getInstance().encodeToString(toXdrByteArray());
  }

  @Override
  public byte[] toXdrByteArray() throws IOException {
    ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
    XdrDataOutputStream xdrDataOutputStream = new XdrDataOutputStream(byteArrayOutputStream);
    encode(xdrDataOutputStream);
    return byteArrayOutputStream.toByteArray();
  }

  public static SurveyRequestMessage fromXdrBase64(String xdr) throws IOException {
    byte[] bytes = Base64Factory.getInstance().decode(xdr);
    return fromXdrByteArray(bytes);
  }

  public static SurveyRequestMessage fromXdrByteArray(byte[] xdr) throws IOException {
    ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
    XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
    return decode(xdrDataInputStream);
  }
}
