// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;

import static org.stellar.sdk.xdr.Constants.*;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.Arrays;
import org.stellar.sdk.Base64Factory;

// === xdr source ============================================================

//  typedef opaque uint256[32];

//  ===========================================================================
public class Uint256 implements XdrElement {
  private byte[] uint256;

  public Uint256() {}

  public Uint256(byte[] uint256) {
    this.uint256 = uint256;
  }

  public byte[] getUint256() {
    return this.uint256;
  }

  public void setUint256(byte[] value) {
    this.uint256 = value;
  }

  public static void encode(XdrDataOutputStream stream, Uint256 encodedUint256) throws IOException {
    int uint256size = encodedUint256.uint256.length;
    stream.write(encodedUint256.getUint256(), 0, uint256size);
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }

  public static Uint256 decode(XdrDataInputStream stream) throws IOException {
    Uint256 decodedUint256 = new Uint256();
    int uint256size = 32;
    decodedUint256.uint256 = new byte[uint256size];
    stream.read(decodedUint256.uint256, 0, uint256size);
    return decodedUint256;
  }

  @Override
  public int hashCode() {
    return Arrays.hashCode(this.uint256);
  }

  @Override
  public boolean equals(Object object) {
    if (!(object instanceof Uint256)) {
      return false;
    }

    Uint256 other = (Uint256) object;
    return Arrays.equals(this.uint256, other.uint256);
  }

  @Override
  public String toXdrBase64() throws IOException {
    return Base64Factory.getInstance().encodeToString(toXdrByteArray());
  }

  @Override
  public byte[] toXdrByteArray() throws IOException {
    ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
    XdrDataOutputStream xdrDataOutputStream = new XdrDataOutputStream(byteArrayOutputStream);
    encode(xdrDataOutputStream);
    return byteArrayOutputStream.toByteArray();
  }

  public static Uint256 fromXdrBase64(String xdr) throws IOException {
    byte[] bytes = Base64Factory.getInstance().decode(xdr);
    return fromXdrByteArray(bytes);
  }

  public static Uint256 fromXdrByteArray(byte[] xdr) throws IOException {
    ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
    XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
    return decode(xdrDataInputStream);
  }
}
