// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;

import static org.stellar.sdk.xdr.Constants.*;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.Objects;
import org.stellar.sdk.Base64;

// === xdr source ============================================================

//  typedef unsigned int uint32;

//  ===========================================================================
public class Uint32 implements XdrElement {
  private XdrUnsignedInteger uint32;

  public Uint32() {}

  public Uint32(XdrUnsignedInteger uint32) {
    this.uint32 = uint32;
  }

  public XdrUnsignedInteger getUint32() {
    return this.uint32;
  }

  public void setUint32(XdrUnsignedInteger value) {
    this.uint32 = value;
  }

  public static void encode(XdrDataOutputStream stream, Uint32 encodedUint32) throws IOException {
    encodedUint32.uint32.encode(stream);
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }

  public static Uint32 decode(XdrDataInputStream stream) throws IOException {
    Uint32 decodedUint32 = new Uint32();
    decodedUint32.uint32 = XdrUnsignedInteger.decode(stream);
    return decodedUint32;
  }

  @Override
  public int hashCode() {
    return Objects.hash(this.uint32);
  }

  @Override
  public boolean equals(Object object) {
    if (!(object instanceof Uint32)) {
      return false;
    }

    Uint32 other = (Uint32) object;
    return Objects.equals(this.uint32, other.uint32);
  }

  @Override
  public String toXdrBase64() throws IOException {
    return Base64.encodeToString(toXdrByteArray());
  }

  @Override
  public byte[] toXdrByteArray() throws IOException {
    ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
    XdrDataOutputStream xdrDataOutputStream = new XdrDataOutputStream(byteArrayOutputStream);
    encode(xdrDataOutputStream);
    return byteArrayOutputStream.toByteArray();
  }

  public static Uint32 fromXdrBase64(String xdr) throws IOException {
    byte[] bytes = Base64.decode(xdr);
    return fromXdrByteArray(bytes);
  }

  public static Uint32 fromXdrByteArray(byte[] xdr) throws IOException {
    ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
    XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
    return decode(xdrDataInputStream);
  }
}
