// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;

import java.io.IOException;

import org.stellar.sdk.Base64Factory;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.Builder;

/**
 * MyStruct's original definition in the XDR file is:
 * <pre>
 * struct MyStruct
 * {
 *     int    someInt;
 *     int64  aBigInt;
 *     opaque someOpaque[10];
 *     string someString&lt;&gt;;
 *     string maxString&lt;100&gt;;
 * };
 * </pre>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
public class MyStruct implements XdrElement {
  private Integer someInt;
  private Int64 aBigInt;
  private byte[] someOpaque;
  private XdrString someString;
  private XdrString maxString;
  public void encode(XdrDataOutputStream stream) throws IOException{
    stream.writeInt(someInt);
    aBigInt.encode(stream);
    int someOpaqueSize = someOpaque.length;
    if (someOpaqueSize != 10) {
      throw new IOException("someOpaque size " + someOpaqueSize + " does not match fixed size 10");
    }
    stream.write(getSomeOpaque(), 0, someOpaqueSize);
    someString.encode(stream);
    int maxStringSize = maxString.getBytes().length;
    if (maxStringSize > 100) {
      throw new IOException("maxString size " + maxStringSize + " exceeds max size 100");
    }
    maxString.encode(stream);
  }
  public static MyStruct decode(XdrDataInputStream stream, int maxDepth) throws IOException {
    if (maxDepth <= 0) {
      throw new IOException("Maximum decoding depth reached");
    }
    maxDepth -= 1;
    MyStruct decodedMyStruct = new MyStruct();
    decodedMyStruct.someInt = stream.readInt();
    decodedMyStruct.aBigInt = Int64.decode(stream, maxDepth);
    int someOpaqueSize = 10;
    decodedMyStruct.someOpaque = new byte[someOpaqueSize];
    stream.readPaddedData(decodedMyStruct.someOpaque, 0, someOpaqueSize);
    decodedMyStruct.someString = XdrString.decode(stream, maxDepth, Integer.MAX_VALUE);
    decodedMyStruct.maxString = XdrString.decode(stream, maxDepth, 100);
    return decodedMyStruct;
  }
  public static MyStruct decode(XdrDataInputStream stream) throws IOException {
    return decode(stream, XdrDataInputStream.DEFAULT_MAX_DEPTH);
  }
  public static MyStruct fromXdrBase64(String xdr) throws IOException {
    byte[] bytes = Base64Factory.getInstance().decode(xdr);
    return fromXdrByteArray(bytes);
  }

  public static MyStruct fromXdrByteArray(byte[] xdr) throws IOException {
    ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
    XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
    xdrDataInputStream.setMaxInputLen(xdr.length);
    return decode(xdrDataInputStream);
  }
}
